Add warning on compressor issue on running an image on a different host
apptainer/singularity-userdocs pull request #104
Opened 2019-02-19 23:46 UTC by devprincess

## Description of the Pull Request (PR):

If the default compressor on a host is not the same on another host, the run command could fail because this compressor is not supported. This is explained now on the build a container section for 3.0. 

## This fixes or addresses the following GitHub issues:

- Fixes #95

2019-02-19 23:47 UTC, devprincess commented
hey @jmstover could you review if this fixes #95 ? thanks !

2019-02-19 23:52 UTC, jmstover requested changes

2019-02-19 23:52 UTC, jmstover commented on build_a_container.rst
> +    Beware that it is possible to build an image on a host and then not running on a different host. This depends on
I think the wording here should be:

```
[...] on a host and have the image not work on a different host. This could be because of the default compressor [...]
```

2019-02-19 23:52 UTC, jmstover commented on build_a_container.rst
> +    Beware that it is possible to build an image on a host and then not running on a different host. This depends on
Other than the wording there, this looks good to me.

2019-02-20 00:35 UTC, jmstover approved these changes

2019-02-20 01:06 UTC, merged