Key search for fingerprints
apptainer/singularity-userdocs pull request #107
Opened 2019-02-26 01:46 UTC by WestleyK

## Description of the Pull Request (PR):

This PR will add more/better `singularity key search` examples, especially for searching for fingerprint.

## This fixes or addresses the following GitHub issues:

- Related to [singularity#2708](https://github.com/sylabs/singularity/issues/2708)

2019-02-26 01:53 UTC, WestleyK commented
Notice in the [signNverify](https://github.com/sylabs/singularity-userdocs/blob/a36a5eef1283289c789c4289c42f9f32b4f2947e/signNverify.rst) page, all of the key commands have the `s` in it, (`keys`, vs `key`). For 3.0.3 thats fine, but for 3.1 that need to change to `key`.

2019-02-26 17:12 UTC, jchavezlavalle requested changes

2019-02-26 17:12 UTC, devprincess commented on signNverify.rst
> +Singularity allows you to search the keystore for plublic keys. You can search for names,
typo on word "public" here

2019-02-26 18:47 UTC, GwendolynK commented on signNverify.rst
> +email, and key IDs (fingerprints). When searching for a fingerprint, you need to use ``0x``
'email' should be plural ('emails'). 

Also, because 'key IDs' are called 'fingerprints' in the following sentence, it doesn't make sense to have 'fingerprints' in parentheses. I suggest changing this either to:
"....emails, and fingerprints (key IDs). ..."
_or_
"...emails, and key IDs, which are also called fingerprints. ..."

2019-02-27 11:40 UTC, jchavezlavalle approved these changes

2019-03-19 11:47 UTC, devprincess commented
@WestleyK is the search still working with the `0x` at the beginning? if that's so then we can merge, otherwise I'll wait the update for the examples :+1:

2019-04-12 19:52 UTC, phpHavok commented
@WestleyK I updated the keys -> key thing in #144 , but my update doesn't include the changes in this PR.

2019-04-13 12:58 UTC, devprincess commented
@phpHavok @WestleyK don't worry guys, I'll update these commands on this section :+1: thanks

2019-04-23 15:10 UTC, jchavezlavalle approved these changes

2019-04-23 15:12 UTC, merged