File for documenting the OCI runtime (WiP)
apptainer/singularity-userdocs pull request #114
Opened 2019-03-19 16:53 UTC by syl-ilumb

## Description of the Pull Request (PR):

Introduce user-facing documentation for OCI runtime support introduced in version 3.1 of Singularity. 

## This fixes or addresses the following GitHub issues:

- Fixes #87

2019-04-05 20:04 UTC, sashayakovtseva commented on oci_runtime.rst
> +.. code-block:: json
Maybe, shorten it somehow? or at least use compact formatting? this json is tooo long :)

2019-04-05 21:10 UTC, syl-ilumb commented on oci_runtime.rst
> +.. code-block:: json
Agreed! https://github.com/sylabs/singularity-userdocs/issues/121.

2019-04-05 21:22 UTC, rherban commented on oci_runtime.rst
> +OCI is an acronym for the `Open Containers Initiative <https://www.opencontainers.org/>`_ - an independent organization whose mandate is to develop open standards relating to containerization. To dat
> It is compliance

either it's compliant or in compliance

2019-04-05 21:22 UTC, rherban commented on oci_runtime.rst
> +OCI is an acronym for the `Open Containers Initiative <https://www.opencontainers.org/>`_ - an independent organization whose mandate is to develop open standards relating to containerization. To dat
I see what you're getting at, but i'm not thrilled about it.

2019-04-05 21:22 UTC, rherban commented on oci_runtime.rst
> +.. code-block:: json
Maybe just link to an example file in github? Does it help to have the full contents listed here?

2019-04-05 21:22 UTC, rherban commented on oci_runtime.rst
> +Currently mounted OCI filesystem bundles can be easily verified:
Maybe we can skip this for the unmount section, since it's detailed above in mount

2019-04-05 21:22 UTC, rherban commented on oci_runtime.rst
> +	The argument provided to ``oci umount`` above is the name of the bundle path, ``/var/tmp/busybox/rootfs``, as opposed to the mount point for the overlay filesystem, ``/var/tmp/busybox/rootfs``.
bundle path is /var/tmp/busybox

2019-04-05 21:22 UTC, syl-ilumb commented on oci_runtime.rst
> +.. code-block:: json
@rherban : Excellent suggestion! Will do.

2019-04-07 18:58 UTC, sashayakovtseva requested changes

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +Owing to this restricted focus, a subset of the Singularity commands in this ``oci`` command group receive attention here; specifically:
command in command group - repetition. is that ok?

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +	- Context for integration with Kubernetes via the Singularity CRI
context you mean is not a subset of commands, so I'd remove it from list here, or rephrase

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +is one way to bootstrap creation of this image in SIF that *retains* a local copy. Additional approaches and details can be found in the section :ref:`Support for Docker and OCI <singularity-and-dock
hm, technically image is not created here but downloaded from cloud to local storage

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +For the purpose of boostrapping the creation of an OCI compliant runtime, this SIF file can be mounted as follows:
OCI runtime compliant container maybe? we do not create runtime here, only a bundle to start a container later

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +By issuing the ``mount`` command, the Singularity container runtime encapsulated in the SIF file ``busybox_latest.sif`` is mounted on the mount point ``/var/tmp/busybox`` as an ``overlay`` file syste
Filesystem is encapsulated into a SIF, not runtime

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +By issuing the ``mount`` command, the Singularity container runtime encapsulated in the SIF file ``busybox_latest.sif`` is mounted on the mount point ``/var/tmp/busybox`` as an ``overlay`` file syste
mounted on the mount point - unnecessary repetition imo

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +	udev                            475192       0    475192   0% /dev
maybe remove all output except for target overlay? not to clutter things with your system's state

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +The *expected* contents of the mounted filesystem are as follows:
why expected? there are no way contents changes unless  oci engine changes

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +The *expected* contents of the mounted filesystem are as follows:
I'd remove expected here

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +From the perspective of the `OCI runtime specification <https://github.com/opencontainers/runtime-spec/blob/master/bundle.md>`_, this content is expected because it prescribes a
prescribes a "... a format" - double article

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +From the perspective of the `OCI runtime specification <https://github.com/opencontainers/runtime-spec/blob/master/bundle.md>`_, this content is expected because it prescribes a
is not expected, but required rather

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +Critical to compliance with the specification is the presence of the following *mandatory* artifacts residing locally in a single directory:
So here you are describing OCI bundle spec, do we really want to do that? I mean, it is already described in OCI spec, we can put a link here...

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +	Because the directory itself, i.e., ``/var/tmp/busybox`` is *not* part of the bundle, the mount point can be chosen arbitrarily.
IMO that is obvious and can be removed

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +The `filtered <https://github.com/stedolan/jq>`_ ``config.json`` file corresponding to the OCI mounted ``busybox_latest.sif`` container can be detailed as follows via ``$ sudo cat /var/tmp/busybox/co
`jq` may not be installed on everyone's system

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +The `filtered <https://github.com/stedolan/jq>`_ ``config.json`` file corresponding to the OCI mounted ``busybox_latest.sif`` container can be detailed as follows via ``$ sudo cat /var/tmp/busybox/co
what does filtered config.json means?

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +Furthermore, and through use of ``$ sudo cat /var/tmp/busybox/config.json | jq [.root.path]``, the property
same as above, `jq` may not be installed, you should use standard commands here

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +.. TODO Is the ``.singularity.d`` ignored in this case? Relates to the other quote I lifted ...
it is not ignored, depends on how you will start the container

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +	- ``ociVersion`` - a mandatory property that identifies the version of the OCI runtime specification that the bundle is compliant with
same as above, I think we don't need to describe OCI standard once and this can be omitted

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +	- ``process`` - an optional property that specifies the container process. When invoked via Singularity, subproperties such as ``args`` are populated by making use of the contents of the ``.singular
It is required when it comes to running containers... See https://github.com/opencontainers/runtime-spec/blob/master/config.md#process

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +	- ``process`` - an optional property that specifies the container process. When invoked via Singularity, subproperties such as ``args`` are populated by making use of the contents of the ``.singular
"When invoked via Singularity, subproperties such as ``args`` are populated by making use of the contents of the ``.singularity.d`` directory" - as far as I know that is not true, @cclerget may tell for sure

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +	- ``process`` - an optional property that specifies the container process. When invoked via Singularity, subproperties such as ``args`` are populated by making use of the contents of the ``.singular
and same for `jq`

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +Technically, the ``overlay`` directory was *not* content expected of an OCI compliant filesystem bundle. As detailed in the section dedicated to `Persistent Overlays <https://www.sylabs.io/guides/3.0
"directory was *not* content expected" - I don't understand what are you trying to say here

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +	SIF is stated to be an extensible format capable of encasulating the entire container runtime in a single file. By encapsulating a filesystem bundle that conforms with the OCI runtime specification,
container filesystem, not runtime. Unless I am missing something...

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +	SIF is stated to be an extensible format capable of encasulating the entire container runtime in a single file. By encapsulating a filesystem bundle that conforms with the OCI runtime specification,
demonstrably evident - tautology, isn't is?

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +SIF files encapsulate filesystem bundles that conform with the OCI runtime specification. By 'OCI mounting' a SIF file (see above), this encapsulated filesystem bundle is exposed. Once exposed, the f
Well, SIF doesn't encapsulate OCI bundles, but can be extracted to it rather. Or bundles can be created based on it, whatever

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +Currently mounted OCI filesystem bundles can be easily verified:
+1

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +	The argument provided to ``oci umount`` above is the name of the bundle path, ``/var/tmp/busybox/rootfs``, as opposed to the mount point for the overlay filesystem, ``/var/tmp/busybox/rootfs``.
+1

2019-04-07 18:58 UTC, sashayakovtseva commented on oci_runtime.rst
> +.. TODO Confirmm the above is OCI standards compliant ^^^
https://github.com/opencontainers/runtime-spec/blob/master/runtime.md#state

2019-04-08 02:43 UTC, GodloveD requested changes
Heya @syl-ilumb thank you for this excellent page!  I think it need some tweaks, but then it should be good to go.  😸

2019-04-08 02:43 UTC, GodloveD commented on oci_runtime.rst
> +Briefly, compliance with respect to the OCI Runtime Specification is addressed in Singularity through the introduction of the ``oci`` command group. Although this command group can in principle be us
`Although this command group can, in principle, be` <-- add commas like so.

2019-04-08 02:43 UTC, GodloveD commented on oci_runtime.rst
> +	- Creating OCI compliant container instances
- ~Creating~ Exposing SIF files to the host file system as OCI compliant container instances 
^ Is this what you mean?

2019-04-08 02:43 UTC, GodloveD commented on oci_runtime.rst
> +Subsequent revisions of this documentation are anticipated to provide more complete coverage of this command group.
I'd just delete this.  Sounds a bit apologetic and there is no need top apologize for this well-written doc imho.

2019-04-08 02:43 UTC, GodloveD commented on oci_runtime.rst
> +.. code-block:: none
imho it is bad form to interrupt a sentence with a code block like this.  I think it should be rewritten so that it does not interrupt the flow like this.

2019-04-08 02:43 UTC, GodloveD commented on oci_runtime.rst
> +For the purpose of illustration, use of `BusyBox <https://busybox.net/about.html>`_ will be made here.
How about
`We'll uses busybox here for purposes of illustration.`
So much easier to parse imho.

2019-04-08 02:43 UTC, GodloveD commented on oci_runtime.rst
> +is one way to bootstrap creation of this image in SIF that *retains* a local copy. Additional approaches and details can be found in the section :ref:`Support for Docker and OCI <singularity-and-dock
Well, technically, a SIF is _created_ from the layers that are downloaded.  But the local copy that is retained is not a SIF.  It's the layers.  So, there is some nuance here that is not quite captured by the text I think.

2019-04-08 02:43 UTC, GodloveD commented on oci_runtime.rst
> +For the purpose of boostrapping the creation of an OCI compliant runtime, this SIF file can be mounted as follows:
The use of the term `bootstrapping` here is a bit confusing.  It's just repackaging a container from one format into another (and losing some info in the process).  It will also be doubly confusing for folks who have been using Singularity for a while because `bootstrap` used to be a command.  And it used to do something totally different.

2019-04-08 02:43 UTC, GodloveD commented on oci_runtime.rst
> +By issuing the ``mount`` command, the Singularity container runtime encapsulated in the SIF file ``busybox_latest.sif`` is mounted on the mount point ``/var/tmp/busybox`` as an ``overlay`` file syste
Echoing @sashayakovtseva here.  It's a root filesystem.  Not a runtime.

2019-04-08 02:43 UTC, GodloveD commented on oci_runtime.rst
> +.. code-block:: json
Just put the `$ sudo cat /var/tmp/busybox/config.json | jq` command into the codeblock as well.  Don't separate it from the output I think.

2019-04-08 02:43 UTC, GodloveD commented on oci_runtime.rst
> +  	"/var/tmp/busybox/rootfs"
Indentation needed on this line.

2019-04-08 02:43 UTC, GodloveD commented on oci_runtime.rst
> +	The outcome of this creation request is truly a container **instance**. Multiple instances of the same container can easily be created by simply changing the name of the instance upon subsequent inv
Is it really an instance though?  I thought we determined it was not. As in, you cannot join this instance with the shell command.

2019-04-08 02:43 UTC, GodloveD commented on oci_runtime.rst
> +The ``state`` of the container instance can be determined via ``$ sudo singularity oci state busybox``:
~busybox~ busybox1

2019-04-08 02:43 UTC, GodloveD commented on oci_runtime.rst
> +Currently mounted OCI filesystem bundles can be easily verified:
Also the phrasing is confusing.  It kindof sounds like this can be verified currently, but we will remove this command in the future or something.  I agree to just remove it.

2019-04-08 02:43 UTC, GodloveD commented on oci_runtime.rst
> +Kubernetes Integration
It seems like you are making a case for using K8s with Singularity.  That's good, but not sure it belongs in a technical manual.  I would suggest leaving it here for now, writing a blogpost (if one doesn't already exist) and then link it here and remove the duplicate content.

2019-04-08 07:53 UTC, cclerget requested changes

2019-04-08 07:53 UTC, cclerget commented on oci_runtime.rst
> +is one way to bootstrap creation of this image in SIF that *retains* a local copy. Additional approaches and details can be found in the section :ref:`Support for Docker and OCI <singularity-and-dock
@GodloveD @syl-ilumb A SIF image is created from OCI image layers and both OCI layers and SIF image are cached locally

2019-04-08 07:53 UTC, cclerget commented on oci_runtime.rst
> +For the purpose of boostrapping the creation of an OCI compliant runtime, this SIF file can be mounted as follows:
`OCI image runtime bundle` ?

2019-04-08 07:53 UTC, cclerget commented on oci_runtime.rst
> +	- ``process`` - an optional property that specifies the container process. When invoked via Singularity, subproperties such as ``args`` are populated by making use of the contents of the ``.singular
In `singularity mount` context, there is two possibilities actually:

1. SIF image contains an OCI image configuration (eg: bootstrapped from docker or OCI registry) so singularity populates `args` with entrypoint/cmd defines in OCI image configuration
2. SIF image doesn't contain OCI image configuration (eg: bootstrapped from scratch or library) so singularity populates `args` with `/.singularity.d/actions/run` as default entrypoint

2019-04-08 07:53 UTC, cclerget commented on oci_runtime.rst
> +Whereas the above is provided via the OCI command group, container instances created in this fashion are still 'known' to Singularity - for example:
This is not true anymore and has been fixed https://github.com/sylabs/singularity/issues/3103. To avoid confusion because `singularity instance` can't interact with OCI containers and vice versa. This block can be removed

2019-04-08 07:53 UTC, cclerget commented on oci_runtime.rst
> +	"A container instance is a persistent and isolated version of the container image that runs in the background." The section on :ref:`Running Services <running_services>` details Singularity's ``inst
Regarding previous comment on `instance`, maybe rephrase this into something like, OCI containers have some similarities with Singularity instances. Or maybe remove it ?

2019-04-08 08:25 UTC, sashayakovtseva commented on oci_runtime.rst
> +	- ``process`` - an optional property that specifies the container process. When invoked via Singularity, subproperties such as ``args`` are populated by making use of the contents of the ``.singular
maybe we should say that upon bundle creation `args` will be filled by singularity automatically. The confusing part for me was `When invoked via Singularity`.

2019-04-08 08:26 UTC, sashayakovtseva commented on oci_runtime.rst
> +.. code-block:: none
agree

2019-04-08 08:28 UTC, sashayakovtseva commented on oci_runtime.rst
> +For the purpose of boostrapping the creation of an OCI compliant runtime, this SIF file can be mounted as follows:
`and losing some info in the process` - what info do we lose? OCI `config.json` is now embedded into a SIF so we don't lose anything

2019-04-08 08:30 UTC, sashayakovtseva commented on oci_runtime.rst
> +	The outcome of this creation request is truly a container **instance**. Multiple instances of the same container can easily be created by simply changing the name of the instance upon subsequent inv
Not singularity instance, but a container object, aka container instance. And we can shell into that container

2019-04-08 13:10 UTC, syl-ilumb commented on oci_runtime.rst
> +.. code-block:: json
@GodloveD : This is a code block formatted via the `json` pygment; if I place `$ sudo cat /var/tmp/busybox/config.json | jq` inside it, it'll also get that `json` pygmentation ...

2019-04-08 13:19 UTC, syl-ilumb commented on oci_runtime.rst
> +.. code-block:: json
@rherban: Great suggestion! Can you please assist?

2019-04-08 13:20 UTC, syl-ilumb commented on oci_runtime.rst
> +.. code-block:: json
@GodloveD: You're looking a tad pale today ... perhaps you could use a little of that old `json` pygmentation ...

2019-04-08 13:20 UTC, sashayakovtseva commented on oci_runtime.rst
> +.. code-block:: json
you can use gist: https://gist.github.com/

2019-04-08 13:24 UTC, syl-ilumb commented on oci_runtime.rst
> +OCI is an acronym for the `Open Containers Initiative <https://www.opencontainers.org/>`_ - an independent organization whose mandate is to develop open standards relating to containerization. To dat
@GwendolynK: Any thoughts on this?

2019-04-08 13:32 UTC, syl-ilumb commented on oci_runtime.rst
> +Currently mounted OCI filesystem bundles can be easily verified:
@GodloveD: From my days as a sysadmin, sanity checks were standard operating procedure; hence, the 'verification'. I have, however, removed this content as requested.

2019-04-08 13:33 UTC, syl-ilumb commented on oci_runtime.rst
> +	The argument provided to ``oci umount`` above is the name of the bundle path, ``/var/tmp/busybox/rootfs``, as opposed to the mount point for the overlay filesystem, ``/var/tmp/busybox/rootfs``.
Apparently, I don't read what I write. Thank you! Fixed.

2019-04-08 13:36 UTC, syl-ilumb commented on oci_runtime.rst
> +.. code-block:: json
Will leave open the comment below re: the length of the `config.json` snippet ...

2019-04-08 13:38 UTC, syl-ilumb commented on oci_runtime.rst
> +Owing to this restricted focus, a subset of the Singularity commands in this ``oci`` command group receive attention here; specifically:
Yes. No. I cleaned this up. Thx @sashayakovtseva.

2019-04-08 13:47 UTC, syl-ilumb commented on oci_runtime.rst
> +is one way to bootstrap creation of this image in SIF that *retains* a local copy. Additional approaches and details can be found in the section :ref:`Support for Docker and OCI <singularity-and-dock
Addressed - thx!

2019-04-08 13:55 UTC, syl-ilumb commented on oci_runtime.rst
> +By issuing the ``mount`` command, the Singularity container runtime encapsulated in the SIF file ``busybox_latest.sif`` is mounted on the mount point ``/var/tmp/busybox`` as an ``overlay`` file syste
According to https://www.sylabs.io/2018/03/sif-containing-your-containers/:

> One of Singularity’s design concepts in architecting a container solution is to  store a container as a single run-time file. 

Given that I can execute a container directly, e.g., `./lolcow.sif`, I'm still thinking that:

> the Singularity container runtime encapsulated in the SIF file 

What am I missing?

2019-04-08 13:57 UTC, syl-ilumb commented on oci_runtime.rst
> +By issuing the ``mount`` command, the Singularity container runtime encapsulated in the SIF file ``busybox_latest.sif`` is mounted on the mount point ``/var/tmp/busybox`` as an ``overlay`` file syste
@sashayakovtseva: Removed redundant use of "mount" and "mount point" ... Thx

2019-04-08 13:59 UTC, syl-ilumb commented on oci_runtime.rst
> +	SIF is stated to be an extensible format capable of encasulating the entire container runtime in a single file. By encapsulating a filesystem bundle that conforms with the OCI runtime specification,
As above ... Perhaps I'm missing something ... Addressed tautological statement ;-)

2019-04-08 14:19 UTC, syl-ilumb commented on oci_runtime.rst
> +SIF files encapsulate filesystem bundles that conform with the OCI runtime specification. By 'OCI mounting' a SIF file (see above), this encapsulated filesystem bundle is exposed. Once exposed, the f
Conferred with @cclerget. Rewrote - be sure to see the note that has the details.

2019-04-08 14:19 UTC, rherban commented on oci_runtime.rst
> +.. code-block:: json
PR131 adds an example json right in the repo.

2019-04-08 14:24 UTC, syl-ilumb commented on oci_runtime.rst
> +.. TODO Confirmm the above is OCI standards compliant ^^^
Added - thank you for that pointer @sashayakovtseva!

2019-04-08 14:25 UTC, syl-ilumb commented on oci_runtime.rst
> +Briefly, compliance with respect to the OCI Runtime Specification is addressed in Singularity through the introduction of the ``oci`` command group. Although this command group can in principle be us
Commas added :-)

2019-04-08 14:26 UTC, syl-ilumb commented on oci_runtime.rst
> +	- Creating OCI compliant container instances
Is revealing OK, @GodloveD?

2019-04-08 14:27 UTC, syl-ilumb commented on oci_runtime.rst
> +Subsequent revisions of this documentation are anticipated to provide more complete coverage of this command group.
That's the Canuck in me - deleted! Thx!

2019-04-08 14:29 UTC, syl-ilumb commented on oci_runtime.rst
> +.. code-block:: none
Used to do this all the time with equations in my past life as a geophysicist ... Nonetheless, majority rules! No more interruption!

2019-04-08 14:31 UTC, syl-ilumb commented on oci_runtime.rst
> +For the purpose of illustration, use of `BusyBox <https://busybox.net/about.html>`_ will be made here.
... but I get paid by the word ... by the word ... by the word ... OK, done.

2019-04-08 14:36 UTC, syl-ilumb commented on oci_runtime.rst
> +	The outcome of this creation request is truly a container **instance**. Multiple instances of the same container can easily be created by simply changing the name of the instance upon subsequent inv
... an OCI container instance ... in other words, an executing container created from the _same_ OCI fs bundle ... isn't that an instance?

2019-04-08 14:38 UTC, syl-ilumb commented on oci_runtime.rst
> +The ``state`` of the container instance can be determined via ``$ sudo singularity oci state busybox``:
Yes - nice catch - thx @GodloveD. Fixed.

2019-04-08 14:38 UTC, syl-ilumb commented on oci_runtime.rst
> +Kubernetes Integration
Fair point. Will address as suggested.

2019-04-08 14:45 UTC, syl-ilumb commented on oci_runtime.rst
> +Whereas the above is provided via the OCI command group, container instances created in this fashion are still 'known' to Singularity - for example:
Block removed

2019-04-08 14:46 UTC, syl-ilumb commented on oci_runtime.rst
> +	"A container instance is a persistent and isolated version of the container image that runs in the background." The section on :ref:`Running Services <running_services>` details Singularity's ``inst
Removed

2019-04-08 14:50 UTC, syl-ilumb commented on oci_runtime.rst
> +	- Context for integration with Kubernetes via the Singularity CRI
Agreed. Moved. Thanks @sashayakovtseva.

2019-04-08 14:54 UTC, syl-ilumb commented on oci_runtime.rst
> +For the purpose of boostrapping the creation of an OCI compliant runtime, this SIF file can be mounted as follows:
Changed to container - thx @sashayakovtseva

2019-04-08 14:57 UTC, syl-ilumb commented on oci_runtime.rst
> +  	"/var/tmp/busybox/rootfs"
Agreed. Fixed.

2019-04-08 15:16 UTC, syl-ilumb commented
Addressed https://github.com/sylabs/singularity-userdocs/pull/114#discussion_r272915745 - thx @cclerget

2019-04-08 15:57 UTC, GodloveD commented on oci_runtime.rst
> +By issuing the ``mount`` command, the Singularity container runtime encapsulated in the SIF file ``busybox_latest.sif`` is mounted on the mount point ``/var/tmp/busybox`` as an ``overlay`` file syste
In that context, run-time is being used as an adjective.  Like a file that can be used at runtime.  In this context you are using run-time as a noun.  That is not correct.  The singularity run-time is what gets invoked when you use the singularity action commands `run, exec, shell, oci start` etc.

It's also important to differentiate between the two, because OCI specifies a spec for the "runtime" and "image format".  And you are talking about a runtime being encapsulated within the SIF image format.  Which it's not.  So it's quite confusing.  

You should really just stick to calling it a "root filesystem" I think.

2019-04-08 17:14 UTC, GwendolynK commented on oci_runtime.rst
> +OCI is an acronym for the `Open Containers Initiative <https://www.opencontainers.org/>`_ - an independent organization whose mandate is to develop open standards relating to containerization. To dat
In this case, saying "compliant" (instead of "is compliance") would be the better choice. 
("It is compliant in the sense of the OCI Specification that is of concern here.")

Another optional edit to make it a little more direct:
"It is compliant with the OCI Runtime Specification that is of concern here."

2019-04-09 01:08 UTC, syl-ilumb commented on oci_runtime.rst
> +By issuing the ``mount`` command, the Singularity container runtime encapsulated in the SIF file ``busybox_latest.sif`` is mounted on the mount point ``/var/tmp/busybox`` as an ``overlay`` file syste
I am now referring to this as a root fs. Upon re-reading what I wrote initially, I now appreciate the confusion caused ... Thx @GodloveD & @sashayakovtseva.

2019-04-09 01:12 UTC, syl-ilumb commented on oci_runtime.rst
> +	SIF is stated to be an extensible format capable of encasulating the entire container runtime in a single file. By encapsulating a filesystem bundle that conforms with the OCI runtime specification,
Clarified - thx

2019-04-09 01:18 UTC, syl-ilumb commented on oci_runtime.rst
> +OCI is an acronym for the `Open Containers Initiative <https://www.opencontainers.org/>`_ - an independent organization whose mandate is to develop open standards relating to containerization. To dat
Improved wording

2019-04-09 01:30 UTC, merged