Add wget to dependency list
apptainer/singularity-userdocs pull request #124
Opened 2019-04-02 17:03 UTC by rherban

## Description of the Pull Request (PR):

Added wget to list of dependencies (required to pull go source)

## This fixes or addresses the following GitHub issues:

- Fixes #112

2019-04-03 04:19 UTC, GodloveD requested changes

2019-04-03 04:19 UTC, GodloveD commented on build_a_container.rst
> +"https://cloud.sylabs.io/library")
I think that this is not correct?  Difference between the frontend and API.  @jscook2345 discussed this in a meeting earlier today and can say for certain.

2019-04-04 21:36 UTC, jchavezlavalle requested changes

2019-04-04 21:36 UTC, devprincess commented on build_a_container.rst
> +"https://cloud.sylabs.io/library")
yea, that reminds me I sent an unnecessary PR to that :smile: , it should remain as `https://library.sylabs.io` since it's the API service afaik

2019-04-05 18:05 UTC, jchavezlavalle approved these changes
lgtm :+1:

2019-04-09 02:32 UTC, GodloveD approved these changes

2019-04-09 02:32 UTC, merged