Tidied up installation page
apptainer/singularity-userdocs pull request #130
Opened 2019-04-05 18:42 UTC by rherban

## Description of the Pull Request (PR):

Clarified commands for installation.
Re-ordered so installation from release is higher focus than from source.
Added wget dependency.

2019-04-09 02:00 UTC, GodloveD requested changes
Suggesting a few tweaks.

2019-04-09 02:00 UTC, GodloveD commented on installation.rst
> +    $ export VERSION=3.0.3 && # adjust this as necessary \
When these changes are made to the 3.1 branch make sure to update all versions to 3.1.1.  It would be really nice if there were some way in Sphynx to set a variable so that all occurrences of something like a version number could be updated.  We had something like that with the old jekyl pages.

2019-04-09 02:00 UTC, GodloveD commented on installation.rst
> +Install Singularity from a release
This heading is not really accurate b/c we are not yet installing.  Maybe `Download Singularity from a release` instead?

2019-04-09 02:00 UTC, GodloveD commented on installation.rst
>  Install from source
Same thing here (and elsewhere if applicable) maybe change Install --> Download

2019-04-09 16:29 UTC, rherban commented on installation.rst
> +    $ export VERSION=3.0.3 && # adjust this as necessary \
versions updated to 3.1.1.

2019-04-11 18:01 UTC, jchavezlavalle approved these changes

2019-04-11 18:06 UTC, GodloveD approved these changes

2019-04-11 18:06 UTC, merged