Add basic plugins information and instructions.
apptainer/singularity-userdocs pull request #150
Opened 2019-04-13 20:38 UTC by phpHavok

## Description of the Pull Request (PR):

This PR adds some basic documentation for the plugin system. All the documentation up to this point is written for a general user. I'm not sure if we want to include developer documentation or not?

## This fixes or addresses the following GitHub issues:

- Fixes #140

2019-04-14 21:39 UTC, GodloveD requested changes
This is terrific @phpHavok!  Thanks for taking the time to look this over and provide some basic documentation.  I have one small suggestion.  After that I think this is good to merge.

2019-04-14 21:39 UTC, GodloveD commented on plugins.rst
> +.. code-block:: none
I would just omit this section because it will likely be hard to keep current and will be out of date a lot, because the user can get this from within Singularity, and because we will auto-generate this kind of documentation using cobra and will place it in the command reference.

2019-04-14 23:02 UTC, phpHavok commented on plugins.rst
> +.. code-block:: none
Sure thing, I've removed it :)

2019-04-14 23:04 UTC, phpHavok commented
No problem, @GodloveD! I fixed the section you mentioned.

2019-04-15 09:30 UTC, jchavezlavalle approved these changes

2019-04-15 09:31 UTC, devprincess commented
lgtm, could you check if all changes are addressed? thanks @GodloveD

2019-04-15 16:13 UTC, GodloveD reviewed
Also, based on a discussion with @bauerm97 this morning, it seems like we would want to direct developers to the following link:

https://godoc.org/github.com/sylabs/singularity/pkg/plugin

This should give information for how to develop plugins.  I've also asked him to look this over and provide a review.

2019-04-15 16:13 UTC, GodloveD approved these changes

2019-04-23 15:56 UTC, bauerm97 commented on plugins.rst
> +    $ singularity plugin compile examples/plugins/test-plugin/
Maybe somewhere around here it would be good (like Dave suggested) to throw a link to the [plugin API's godoc page](https://godoc.org/github.com/sylabs/singularity/pkg/plugin). Of course this documentation is focusing on _using_ plugins rather than _developing_, but it's a nice touch. I think it'd be great to have a sentence like this:

>For people who wish to develop their own plugins, developer documentation is currently being written. However, please reference the [godoc](https://godoc.org/github.com/sylabs/singularity/pkg/plugin) to get started in the mean time

Something like that which says that we're working on actual developer docs (are we? we should be :D) and that the godoc is a good starting point. I trust you to figure out good phrasing and the best spot to include that. Cheers!

2019-04-23 23:17 UTC, phpHavok commented on plugins.rst
> +    $ singularity plugin compile examples/plugins/test-plugin/
@bauerm97: Sure thing! It seemed appropriate to create a short, separate section on writing a plugin at the end. In the future, we could potentially just provide a link to the complete developer documentation in case a developer is browsing the user documentation. Let me know what you think.

By the way, I'd be more than happy to write some tutorial-style documentation for plugins if you want. I'm just sure where to put it or what format to write in (RST, Markdown, something else?).

2019-04-30 15:20 UTC, GodloveD commented
Looks good @phpHavok.  Thanks for the improvements.

2019-04-30 15:20 UTC, merged