Add multi-stage build
apptainer/singularity-userdocs pull request #160
Opened 2019-05-01 01:03 UTC by rherban

## Description of the Pull Request (PR):

Adding documentation for multi-stage builds.  

## This fixes or addresses the following GitHub issues:

- Fixes #143

2019-05-03 13:50 UTC, devprincess commented on definition_files.rst
> +.. code-block:: singularity
Maybe check the indentation around the def file? thanks @rherban

2019-05-03 15:34 UTC, rherban commented
Add comment to files to copy from another image.
add 'stage' to the header section

2019-05-09 15:28 UTC, rherban commented
@GodloveD @devprincess your comments have been addressed, please re-review when you can.

2019-05-09 17:28 UTC, jchavezlavalle approved these changes

2019-05-09 17:29 UTC, devprincess commented
lgtm, thanks :+1: @rherban

2019-05-15 14:21 UTC, ikaneshiro requested changes
We should add something easily seen at the very top of this page that says:
`In order to facilitate the new multi-stage build feature, the definition parser in 3.2+ now requires "Bootstrap" to be the first parameter of header. This breaks compatibility with previous definition parsers that allow the parameters of the header to appear in any order.`

2019-05-15 14:21 UTC, ikaneshiro commented on definition_files.rst
> +The stage names are arbitrary and files can be copied from any stage to another.
We should change this line to something like:
`The names of stages are arbitrary. Files can only be copied from stages declared before the current stage in the definition. E.g., the "devel" stage in the above definition cannot copy files from the "final" stage, but the "final" stage can copy files from the "devel" stage.`

2019-05-15 14:48 UTC, rherban commented
> We should add something easily seen at the very top of this page that says:
> `In order to facilitate the new multi-stage build feature, the definition parser in 3.2+ now requires "Bootstrap" to be the first parameter of header. This breaks compatibility with previous definition parsers that allow the parameters of the header to appear in any order.`

To clarify @ikaneshiro, Bootstrap has to be first regardless if you're using multi-stage?  Did that get called out as a breaking change?

2019-05-15 17:27 UTC, ikaneshiro commented
@rherban Yes for any build with a header, and this is a known breaking change and was encountered and discussed here https://github.com/sylabs/singularity/pull/3377

2019-05-15 18:23 UTC, rherban commented
I didn't see anything in the release notes on this and agree that something should have been said to users aren't left wondering why things changed after the upgrade.  I have updated based on your others comments @ikaneshiro .

2019-05-15 19:14 UTC, ikaneshiro commented
@rherban It was added to the changelog, but it looks like it wasn't mentioned in the release announcement which maybe it should have been. Understandable though since the security issue was so important it was probably the last thing on @GodloveD's mind

2019-05-15 20:13 UTC, GodloveD commented
I'm actually not seeing this in the `CHANGELOG.md` either 😞.  But yeah, we totally need to make users aware of it.

2019-05-15 20:16 UTC, ikaneshiro commented
@GodloveD https://github.com/sylabs/singularity/blob/master/CHANGELOG.md#new-features--functionalities Its there, sub bullet of the second bullet point

2019-05-15 20:16 UTC, GodloveD requested changes

2019-05-15 20:16 UTC, GodloveD commented on definition_files.rst
> +    EOF
The whitespace in front of this EOF breaks the def file.  Can you remove?

2019-05-16 00:39 UTC, GodloveD commented
Oh hot damn @ikaneshiro !!  Great!  I missed that.

2019-05-16 00:41 UTC, GodloveD approved these changes
:shipit:

2019-05-16 13:59 UTC, ikaneshiro requested changes
One nitpick, lgtm otherwise

2019-05-16 13:59 UTC, ikaneshiro commented on definition_files.rst
> +The names of stages are arbitrary. Files can only be copied from stages declared before the current stage in the definition. E.g., the "devel" stage in the above definition cannot copy files from the
Can you quote the quotted text using markdown syntax so it looks like `devel`, `final`, etc. I used double quotes in my last comment since github comments also interpret markdown and it would have gotten confused.

2019-05-16 15:27 UTC, ikaneshiro approved these changes

2019-05-16 19:27 UTC, merged