adding note on cache commands
apptainer/singularity-userdocs pull request #164
Opened 2019-05-03 14:57 UTC by devprincess

## Description of the Pull Request (PR):

This one is to fix #163 : When building a container with sudo privileges, the cache commands should consider the use of sudo as well. Default location of cache is `~/.singularity/cache` whereas for sudo privilege is `/root/.singularity/cache`

## This fixes or addresses the following GitHub issues:

- Fixes #163

2019-05-03 15:41 UTC, GodloveD requested changes
I think it could actually be spelled out a little more clearly to the user (actually include the command?)

2019-05-07 15:28 UTC, GodloveD approved these changes
lgtm

2019-05-07 15:29 UTC, merged

2019-05-07 19:55 UTC, WestleyK reviewed
Sorry I'm kinda late for the review, maybe make another PR fixing the comments?... These are just some suggestions :+1:

2019-05-07 19:55 UTC, WestleyK commented on build_env.rst
> +        Total space used: 0.00 kB
This looks like the output for `cache list`, not `cache clean`. I would just remove all the output for the `cache clean` command.

2019-05-07 19:55 UTC, WestleyK commented on build_env.rst
> +    Make sure that if you build a container with sudo privilege, you will need to consider the sudo location from the cache, and not the default.
I would changes this up a bit:

```suggestion
    If you build a container with sudo privilege (like a definition file), you cache will be stored in your root directory (``/root/.singularity/cache``) and not your home directory.

```

2019-05-07 19:55 UTC, WestleyK commented on build_env.rst
> +    For example, running the following command with sudo privilege (considering the sudo privilege location for cache ``/root/.singularity/cache``):
I would take this out of the `note` block, and change it like this:

```suggestion
For example, running a action (``exec``, ``pull``, ``run``, etc...), command with sudo (or as root), cache will be stored in ``/root/.singularity/cache``, _if the ``SINGULARITY_CACHEDIR`` is **not** set._
```

You can add to that, and changes as you see fit :+1:

2019-05-07 19:55 UTC, WestleyK commented on build_env.rst
> +    and then cleaning the cache without sudo privilege (``singularity cache clean -a``) will not work, since the default cache location is ``~/.singularity/cache``.
Again, I would remove the spaces before the text, and change it like:

```suggestion
If you set ``SINGULARITY_CACHEDIR`` to something like ``SINGULARITY_CACHEDIR=/tmp/image-cache``, then all cache will be stored in `/tmp/image-cache`. Remember, when you use sudo, to add `-E` flag to your singularity command, like ``sudo -E singularity build test.sif test.def``.
```

And/or add a link to the page where it talks about `SINGULARITY_CACHEDIR`.

*These are just my suggestions, you can change it as you see fit.*

2019-05-07 19:55 UTC, WestleyK commented on build_env.rst
> +    In this case you would need to run the clean command with sudo privilege:
```suggestion
For example cleaning you cache in ``/root/.singularity/cache``:
```

2019-05-07 19:55 UTC, WestleyK commented on build_env.rst
> +    .. code-block:: none
```suggestion
.. code-block:: none
```

2019-05-07 19:55 UTC, WestleyK commented on build_env.rst
> +        $ sudo singularity cache clean -a
And also add a example when `SINGULARITY_CACHEDIR` is set:

```
    # And with 'SINGULARITY_CACHEDIR' set, use the '-E' flag for sudo:
    $ sudo -E singularity cache clean --all
```

2019-05-07 19:55 UTC, WestleyK commented on build_env.rst
> +        ubuntu_18.04.sif       2019-01-31 14:58:44    27.98 Mb         library
I would update the output for the cache list command: *Add the summary after the cache*

```
    $ sudo singularity cache list 
NAME                     DATE CREATED           SIZE             TYPE
ubuntu_latest.sif        2019-05-07 12:53:14    28.11 MB         library
ubuntu_18.04.sif         2019-05-07 12:53:24    27.98 MB         library

There 2 containers using: 56.09 MB, 0 oci blob file(s) using 0.00 kB of space.
Total space used: 56.09 MB
```