Remote endpoint docs
apptainer/singularity-userdocs pull request #168
Opened 2019-05-09 14:34 UTC by rherban

## Description of the Pull Request (PR):

Adding docs for `remote` commands for managing remote endpoints

## This fixes or addresses the following GitHub issues:

- Fixes #113

2019-05-09 14:50 UTC, jchavezlavalle requested changes
couple suggestions, thanks @rherban !

2019-05-09 14:50 UTC, devprincess commented on endpoint.rst
> +
might be useful to add the output of each command? for say in this case `remote list` will list only one remote uri, then when adding a new one, after running the `remote list` command once again you will see from the output that it has been correctly added. @rherban

2019-05-09 14:50 UTC, devprincess commented on endpoint.rst
> +stored in ``singularity/etc/remote.yaml`` file.
think this path should be updated to `~/.singularity/etc/remote.yaml`

2019-05-15 18:26 UTC, rherban commented on endpoint.rst
> +
I'm going to skip this for now, just so we can get something published.

2019-05-16 00:37 UTC, GodloveD requested changes
make sure to add this to the index as well so that it shows up in the TOC.   I'll do a more thorough review later.

2019-05-16 10:59 UTC, jchavezlavalle approved these changes

2019-05-24 15:43 UTC, WestleyK requested changes
Looks good, have a couple suggestions/comments :+1:

2019-05-24 15:43 UTC, WestleyK commented on endpoint.rst
> +- ``build -remote`` - To build SIF via Remote Builder
```suggestion
- ``build --remote`` - To build SIF via Remote Builder
```

2019-05-24 15:43 UTC, WestleyK commented on endpoint.rst
> +
Technically `verify` also uses endpoints to download the key. (if there is no `--local` flag)

2019-05-24 15:43 UTC, WestleyK commented on endpoint.rst
> +    $ singularity remote status name
Maybe add something at the bottom of the page, like:

```
Now your endpoint is configured to... you can push/pull...
```

2019-05-24 15:43 UTC, WestleyK commented on endpoint.rst
> +Before using an endpoint, you'll need to ``login`` to it.  This will require
Is there a reason for a extra space here? If not:

```suggestion
Before using an endpoint, you'll need to ``login`` to it. This will require
```

2019-05-24 15:43 UTC, WestleyK commented on endpoint.rst
> +    ``docker://`` and ``shub://`` prefixes are unaffected by these commands
What about ORAS?  <- @ikaneshiro

2019-05-24 15:43 UTC, WestleyK commented on endpoint.rst
> +This page will describe the <subcommands> under  ``Remote`` command group.
```suggestion
This page will describe the <subcommands> under ``remote`` command group.
```

2019-05-24 17:47 UTC, WestleyK requested changes

2019-05-24 17:47 UTC, WestleyK commented on endpoint.rst
> +stored in ``~/.singularity/etc/remote.yaml`` file.
I believe the path is this: 

```suggestion
stored in ``~/.singularity/remote.yaml`` file.
```

2019-05-24 18:17 UTC, ikaneshiro commented on endpoint.rst
> +    ``docker://`` and ``shub://`` prefixes are unaffected by these commands
Also unaffected, but not in 3.2 which is what I think this specific doc page is for

2019-05-24 18:54 UTC, ikaneshiro requested changes
Couple nitpicks

2019-05-24 18:54 UTC, ikaneshiro commented on endpoint.rst
> +The remote command group manages these endpoints. The configurations are usually
Lets highlight this
```suggestion
The ``remote`` command group manages these endpoints. The configurations are usually
```

2019-05-24 18:54 UTC, ikaneshiro commented on endpoint.rst
> +
`exec/shell/run/instance` will use the remote endpoint as well if a `library` URI is specified and not a local image.

2019-05-24 18:54 UTC, ikaneshiro commented on endpoint.rst
> +    $ singularity remote status name
```suggestion
    $ singularity remote status <remote_name>
```

2019-05-24 19:00 UTC, WestleyK commented on endpoint.rst
> +    $ sudo singularity remote add -g <remote_name> <remote_uri>
Do you need `sudo` here? If so, can you add a expiation on why you need it?

2019-05-24 19:21 UTC, ikaneshiro commented on endpoint.rst
> +    $ sudo singularity remote add -g <remote_name> <remote_uri>
@WestleyK yes because the global remote config is only modifiable to the root user

2019-05-24 19:24 UTC, rherban commented on endpoint.rst
> +    $ sudo singularity remote add -g <remote_name> <remote_uri>
I believe it has to edit this config as root: /usr/local/etc/singularity/remote.yaml

Tested locally and it yells at me to use root.

2019-06-01 16:22 UTC, devprincess commented
@rherban @sushma-98 hey guys what's the status on this one? is it ready to go? thanks!

2019-06-01 20:56 UTC, sushma-4 commented
@devprincess Made the final changes and sent it to @rherban. The PR is through his repo, so as soon as he updates it, we are good to go.

2019-06-04 21:39 UTC, WestleyK requested changes
Couple last suggestions... Looking good :+1:

2019-06-04 21:39 UTC, WestleyK commented on endpoint.rst
> +    endpoint using **sudo**, you must ``list`` it using **sudo** as well.
Should `sudo` be in the code format? For consistency

```suggestion
    endpoint using ``sudo``, you must ``list`` it using ``sudo`` as well.
```

2019-06-04 21:39 UTC, WestleyK commented on endpoint.rst
> +     be viewed in ``remote.yaml`` file.
Should you show the full path to this file?

2019-06-04 21:39 UTC, WestleyK commented on endpoint.rst
> +To ``add`` an global endpoint (available to all users on the system):
I think you can replace `an`, with `a`:

```suggestion
To ``add`` a global endpoint (available to all users on the system):
```

2019-06-04 21:39 UTC, WestleyK commented on endpoint.rst
> +    the commands either with or without ``sudo`` privilege. If you ``Add`` an
```suggestion
    the commands either with or without ``sudo`` privilege. If you ``add`` an
```

2019-06-05 04:50 UTC, GodloveD approved these changes
I just tacked a commit onto the end of this PR with a few minor edits.  Some for branding and some for clarity.  I think this is good to go with these changes.

2019-06-05 10:22 UTC, sushma-4 commented on endpoint.rst
> +    endpoint using **sudo**, you must ``list`` it using **sudo** as well.
Right we can just write sudo in bold. I changed all sudo(s) to bold for consistency. Thank yo

2019-06-05 10:33 UTC, merged