added sign, verify, and keys, example page
apptainer/singularity-userdocs pull request #19
Opened 2018-10-08 20:36 UTC by GodloveD

Heads up @devprincess!

2018-10-08 21:00 UTC, jchavezlavalle requested changes

2018-10-08 21:00 UTC, jchavezlavalle commented on signNverify.rst
> +
@GodloveD I think what's missing is saying F goes for fingerprint and then something like "you should copy this fingerprint to use it as a key at the moment of pushing the container" Not so sure if other fields would be important to mention as well ( U user, C Creation date, F fingerprint as said and L for length of the key)

2018-10-08 21:00 UTC, yhcote requested changes
Just a few suggestions.

2018-10-08 21:00 UTC, yhcote commented on signNverify.rst
> +In this example you can see that Sylabs Admin has signed the container.
... and that the locally computed hash matches the one signed at creation.

(Or something that means that)

2018-10-08 21:00 UTC, yhcote commented on signNverify.rst
> +To sign your own containers you first need to generate one or more keys.
Doing "singularity sign x.sif" will guide the user go though all that simply by answering questions on the command line if no keys are found. Do you wanna mention that and then say, this is how you do it manually or when you add more keys?

2018-10-08 21:08 UTC, devprincess commented on signNverify.rst
> +
Oh, also forgot on this same thing to add something like the `singularity keys list` command will list you the keys you have generated, although evident I think is important to be pointed out to the users, otherwise they could expect just one key all the time but in reality they can generate many pairs

2018-10-09 01:22 UTC, GodloveD commented on signNverify.rst
> +To sign your own containers you first need to generate one or more keys.
Nice. Thanks

2018-10-09 01:22 UTC, GodloveD commented on signNverify.rst
> +
Right on both counts.

2018-10-09 01:32 UTC, yhcote approved these changes
Looks good to me!

2018-10-09 08:24 UTC, jchavezlavalle approved these changes

2018-10-09 08:26 UTC, merged