Updated the Quick-start guide
apptainer/singularity-userdocs pull request #191
Opened 2019-06-10 21:41 UTC by sushma-4

## Description of the Pull Request (PR):

Updated the quick guide so that the installation is described in the simplest way possible. Also changed some command syntax supported by newer versions, updated the hyperlinks and interlinks to different sections of the docs.

## This fixes or addresses the following GitHub issues:

- Fixes #
#188

2019-06-11 14:10 UTC, jchavezlavalle requested changes
left some comments around @sushma-4 thanks!

2019-06-11 14:10 UTC, jchavezlavalle commented on quick_start.rst
> +     different methods of Installtion, versions, and RPM etc, please refer to
typo on word Installation

2019-06-11 14:10 UTC, jchavezlavalle commented on quick_start.rst
> +Set the Environment variable PATH to point to Go:
better use ``PATH`` notation with the `` quotes

2019-06-11 18:20 UTC, WestleyK reviewed
Looks good, couple suggestions/questions...

2019-06-11 18:20 UTC, WestleyK commented on quick_start.rst
> +3. :ref:`Compiling Singularity Binaries <compile>`
Source code maybe?

```suggestion
3. :ref:`Compiling Singularity Source Code <compile>`
```

2019-06-11 18:20 UTC, WestleyK commented on quick_start.rst
> +    source ~/.bashrc
Why did you change this command?

2019-06-11 18:20 UTC, WestleyK commented on quick_start.rst
>  Compile the Singularity binary
Source code maybe?

```suggestion
Compile the Singularity source code
```

2019-06-11 21:09 UTC, sushma-4 commented on quick_start.rst
> +    source ~/.bashrc
There was no need to set GOPATH, just making the PATH = /usr/local/go/bin was enough.. idk did you have to set the GOPATH too for your installation?

2019-06-11 22:39 UTC, WestleyK commented on quick_start.rst
> +    source ~/.bashrc
First, you dont want you PATH to only be `/usr/local/go/bin`, it should be `PATH=/usr/local/go/bin:${PATH}`.

Second, if you installing Go, you should do it the right way and setup all your PATHs, eg. `GOPATH`. Imo

CC/Ping @GodloveD, @devprincess

2019-06-12 00:12 UTC, GodloveD requested changes
Thanks for these changes @sushma-4.  I agree with most of them, but there are others I think should be reverted.  I think the `wget` command should remain as a more efficient way to download singularity.  Also I really don't think we want to replace internal links with external links.  If we do so we will need to update all of the external links every time we update the docs versions or all of our links will be pointing to older versions of the docs.  Better to just fix the internal references if they are busted.

2019-06-12 00:12 UTC, GodloveD commented on quick_start.rst
> +     different methods of Installation, versions, and RPM etc, please refer to
Change Installation to lowercase (installation) on line 30 plz

2019-06-12 00:12 UTC, GodloveD commented on quick_start.rst
> +    Note that ``squashfs-tools`` is only a dependency for commands that builds
~builds~ build (it was right the first time since _commands_ is plural.  😄 )

2019-06-12 00:12 UTC, GodloveD commented on quick_start.rst
> +    $  sudo tar -C /usr/local -xzvf go1.12.5.linux-amd64.tar.gz
I'm not convinced that that is an improvement over the `wget` method.  With the previous version, I can simply copy and paste the 4 line command and I'm done.  With these changes I have to navigate away from this page, manually download a file with a click, figure out where it went, and then copy it to where I want it before I even execute the command above.  Even worse, this workflow is not captured in the instructions here so I have to just figure it out.

2019-06-12 00:12 UTC, GodloveD commented on quick_start.rst
> +    source ~/.bashrc
I'm OK with this more minimal method.  Maybe it is not "the right way", but maybe this _is_ the right way now that Go modules exist.  And it's not really our responsibility to make sure that people set their Go env up properly.  We just want to make sure they can install Singularity.  We also give several links to Go docs so people can look there if they want the official Golang way to install Go.

2019-06-12 00:12 UTC, GodloveD commented on quick_start.rst
> +Singularity’s command line interface allows you to build
Why remove this link?  Is it dead?  Can you just fix it instead?

2019-06-12 00:12 UTC, GodloveD commented on quick_start.rst
> +and `build <https://www.sylabs.io/guides/3.2/user-guide/cli/singularity_build.html>`_
We really don't want to put these external links in here imho because they are much more prone to break. We just want to fix the internal links if they are broken. Otherwise these are going to break every time we update the docs to a new version for instance. Fixing the internal links if much more future-proof.

2019-06-12 00:12 UTC, GodloveD commented on quick_start.rst
> -Library, ``pull`` simply downloads the image file to your system.
I don't understand this deletion.

2019-06-12 00:12 UTC, GodloveD commented on quick_start.rst
> +from scratch using a :ref:`definition file <definitionfiles>`. You can also
yay!!

2019-06-12 00:12 UTC, GodloveD commented on quick_start.rst
> +performs things like software installation, environment setup, and copying files
~performs~ -> perform (because _sections_ is plural).

2019-06-12 11:39 UTC, sushma-4 commented on quick_start.rst
> +    $  sudo tar -C /usr/local -xzvf go1.12.5.linux-amd64.tar.gz
Right, the commands are definitely easier to work with, but for somebody who's not good with commands(students I held workshop for, even myself in the very beginning) it was easier to understand what was happening the UI way, but again there are people who would simply want to copy the commands, so I added comments on what each of those commands meant. Is that okay?

2019-06-12 11:42 UTC, sushma-4 commented on quick_start.rst
> +    source ~/.bashrc
The link to Go Installation page is included in this section. Thank you @GodloveD

2019-06-12 11:46 UTC, sushma-4 commented on quick_start.rst
> +and `build <https://www.sylabs.io/guides/3.2/user-guide/cli/singularity_build.html>`_
Agree! I totally wanted to do it with internal links.... because these are auto generated pages.. they don't have a ``rst`` page in the Repo. Is there any other way we can do it?

2019-06-12 11:48 UTC, sushma-4 commented on quick_start.rst
> +performs things like software installation, environment setup, and copying files
OMG I shouldn't mess with English Grammar

2019-06-12 11:55 UTC, sushma-4 commented on quick_start.rst
> +Singularity’s command line interface allows you to build
The link was probably from the page that was replaced my auto generated cli docs.. I manually checked every doc page, but couldn't find it.. maybe I should create a new link to the main CLI page and link it here.

2019-06-12 12:10 UTC, sushma-4 commented on quick_start.rst
> -Library, ``pull`` simply downloads the image file to your system.
Me neither :/ Maybe I was trying to add it after the command and forgot. Sorry

2019-06-13 03:45 UTC, GodloveD commented on quick_start.rst
> +and `build <https://www.sylabs.io/guides/3.2/user-guide/cli/singularity_build.html>`_
You need to make a reference to the place you want to link to and then use that reference in the RST docs.  There are lots of existing examples sprinkled throughout the docs right now.

2019-06-17 13:30 UTC, devprincess commented on quick_start.rst
> +and `build <https://www.sylabs.io/guides/3.2/user-guide/cli/singularity_build.html>`_
@sushma-4 you should just add a variable in replacements.py and then reference where needed, with that we would avoid having to update in every single place :+1:

2019-06-17 16:09 UTC, sushma-4 commented on quick_start.rst
> +and `build <https://www.sylabs.io/guides/3.2/user-guide/cli/singularity_build.html>`_
I actually tried using ``replace`` so that a variable can be replaced, just tried the method you suggested, but while reading the URL, its not substituting the value.

Its getting read as special characters:
https://www.sylabs.io/guides/ **%7Bversion%7D** /

2019-06-18 13:14 UTC, devprincess commented on quick_start.rst
> +and `build <https://www.sylabs.io/guides/3.2/user-guide/cli/singularity_build.html>`_
yes this was solved by considering the following changes: on the `replacements.py` consider this declaration:

```
variable_replacements = {
    "{InstallationVersion}" : "3.2.0"
    "\{version\}" : "3.2"
}
``` 
and then on the rst just call the variable on the link ref as:

```
`pull <https://www.sylabs.io/guides/\{version\}/user-guide/cli/singularity_pull.html>`_
```

2019-06-18 21:22 UTC, WestleyK approved these changes
Looks good to me :+1:

2019-06-18 23:09 UTC, GodloveD requested changes
I still think the internal links should not be referencing an external URI.  See my comments inline for details.

2019-06-18 23:09 UTC, GodloveD commented on quick_start.rst
> +and `build <https://www.sylabs.io/guides/3.2/user-guide/cli/singularity_build.html>`_
Wait.  I don't think we want to do this either.  RST provides a shorthand way to make internal links right?  There is no need to spell out the whole external link like this.  Plugging in the version variable helps, but it's still not a great solution. 

Look at line 13 in the `quickstart.rst`
```
:ref:`requesting an installation help page <installation-request>`
```
This corresponds to a reference in `installation.rst` at line 497:
```
.. _installation-request:
```
This is the strategy that I think we need to use throughout to avoid broken links.  This way even if we change the location of the entire web page the internal links will still not break.

2019-06-19 00:12 UTC, GwendolynK-zz requested changes

2019-06-19 00:12 UTC, GwendolynK-zz commented on installation.rst
>  completely remove Singularity.
```suggestion

```
This exact phrase was used in the sentence before. There isn't a need to repeat. One other note, to remain grammatically correct when removing this section of the sentence, we also need to remove the 'to' that proceeds it on the line right before. 
End sentence should be "For example, in a standard installation of Singularity 3.0.1 and beyond (when building from source) you must remove all of these files and directories."

2019-06-19 00:12 UTC, GwendolynK-zz commented on quick_start.rst
> +     different methods of installation, versions, and RPM etc, please refer to
```suggestion
     different methods of installation, versions, RPMs, etc, please refer to
```
@WestleyK is this still accurate technically? It is grammatically now...

2019-06-19 00:12 UTC, GwendolynK-zz commented on quick_start.rst
> +    other commands may do so as well if they are run using container images
```suggestion
    other commands may do so as well if they are ran using container images
```
or 
```suggestion
    other commands may do so as well if they are running using container images
```

2019-06-19 00:12 UTC, GwendolynK-zz commented on quick_start.rst
> +You can interact with images in several ways each of which can accept image URIs
```suggestion
You can interact with images in several ways, each of which can accept image URIs
```
Helps sentence flow.

2019-06-19 00:12 UTC, GwendolynK-zz commented on quick_start.rst
>  command, or simply by  calling the container as though it were an executable.
```suggestion
 command, or simply by calling the container as though it were an executable.
```
extra space

2019-06-19 00:12 UTC, GwendolynK commented on quick_start.rst
> +into the container from host system etc.
```suggestion
into the container from host system, etc.
```

2019-06-19 00:12 UTC, GwendolynK commented on installation.rst
> +for downloading and running VMs with singularity pre-installed from `Vagrant
```suggestion
for downloading and running VMs with Singularity pre-installed from `Vagrant
```

2019-06-19 12:11 UTC, sushma-4 commented on installation.rst
>  completely remove Singularity.
Thanks for the review @GwendolynK 
Does this sound better?
 
In a standard installation of Singularity 3.0.1 and beyond (when
building from source), the command ``sudo make install`` lists all the files as
they are installed. You must remove all of these files and directories to
completely remove Singularity.

2019-06-20 20:14 UTC, sushma-4 commented on quick_start.rst
> +     different methods of installation, versions, and RPM etc, please refer to
I'm referring to https://sylabs.io/guides/3.2/user-guide/installation.html#build-and-install-an-rpm on our installation page. It should be just RPM IMO

2019-06-20 20:20 UTC, GwendolynK-zz approved these changes

2019-06-20 20:23 UTC, merged