First version of the MPI documentations
apptainer/singularity-userdocs pull request #192
Opened 2019-06-12 01:17 UTC by gvallee

## Description of the Pull Request (PR):

This adds a basic section about Singularity and MPI. While it is far from being complete, it might be a good candidate for a first version of the MPI documentation that we will extend over time.

## This fixes or addresses the following GitHub issues:

- Addresses #77

2019-06-14 20:36 UTC, GodloveD requested changes
This a great start!  I have some quick knee-jerk reactions just to get the ball rolling.

2019-06-14 20:36 UTC, GodloveD commented on mpi.rst
> +the ``Hybrid`` model since both the MPI implementations provided by System
I think we want to reserve the use of double backticks for names of commands or inline code snippets.  Maybe bold, italics, or double quotes would work better for **Host MPI** and **Hybrid** above.

2019-06-14 20:36 UTC, GodloveD commented on mpi.rst
> +  not an option on high-performance computing platforms.
This note is a little funny because lots of HPC workflows require file sharing between the container and host.  This is a pretty standard practice afaik.

2019-06-14 20:36 UTC, GodloveD commented on mpi.rst
> +1. ``mpirun`` is called by the resource manager or the user directly from a shell
Or `mpiexec` or a similar launcher right?

2019-06-14 20:36 UTC, GodloveD commented on mpi.rst
> +    configured for optimal use of the hardware if performance is critical.
It seems weird to capitalize MUST here when this is really only a requirement in as much as performance is critical.  Many users may care more about portability than performance if they are containerizing MPI jobs.

2019-06-14 20:36 UTC, GodloveD commented on mpi.rst
> +	    cd /opt && mpicc -o mpitest mpitest.c
def file above has some wonky indentation that makes it hard to read.  (Mix of tabs and spaces?)
![TabsSpacesBoth](https://user-images.githubusercontent.com/7672924/59536151-2d7bff00-8eb0-11e9-9466-036da814cdb1.png)

2019-06-14 20:36 UTC, GodloveD commented on mpi.rst
> +        cd /tmp/ompi/openmpi-$OMPI_VERSION && ./configure --prefix=$OMPI_DIR && make -j8 install
I don't know if you want to assume that a user has at least 8 processors here.

2019-06-14 20:36 UTC, GodloveD commented on mpi.rst
> +        export OMPI_DIR
How come this one is exported on a different line while all the others are exported on the same line on which they are set.  (NitPick, I know.)

2019-06-14 20:36 UTC, GodloveD commented on mpi.rst
> +	    cd /tmp/mpich/mpich-$MPICH_VERSION && ./configure --prefix=$MPICH_DIR && make -j8 install
Not sure if we should include the `-j8` because we don't know how many processors user will have?

2019-06-14 20:36 UTC, GodloveD commented on mpi.rst
> +by the ``NP`` environment variable.
Might want to add the slurm command to submit the script just to round the example out.

2019-06-14 20:36 UTC, GodloveD commented on mpi.rst
> +by the ``NP`` environment variable.
It would be cool if this doc had a second section describing a second strategy for containerizing MPI completely (along with advantages and caveats of this approach, etc.)  Here are some cliff's notes from @AdamSimpson's talk at SUG.
```
HOSTFILE=".hostfile.${SLURM_JOB_ID}"
for host in $(scontrol show hostnames); do
    echo "${host}" >>${HOSTFILE}
done

OMPI_MCA_plm=rsh
OMPI_MCA_plm_rsh_args='-o PubKeyAcceptedKeyTypes=+ssh-ds -o ...'
OMPI_MCA_orte_launch_agent="singularity run --nv nvidia.simg orted"

singularity run nvidia.simg mpirun --hostfile $HOSTFILE cmd
```

2019-06-22 01:25 UTC, gvallee commented on mpi.rst
> +  not an option on high-performance computing platforms.
Very true and it deserves a little clarification I think. I will try to improve the wording.

2019-06-22 01:25 UTC, gvallee commented on mpi.rst
> +1. ``mpirun`` is called by the resource manager or the user directly from a shell
Correct, I will improve the wording.

2019-06-22 01:27 UTC, gvallee commented on mpi.rst
> +        export OMPI_DIR
My best answer will be because I used a def file that I wrote when I was not that much familiar with containers ;) I will make it consistent

2019-06-22 01:28 UTC, gvallee commented on mpi.rst
> +by the ``NP`` environment variable.
Do you want that in the first version of the documentation or in v2? I do not mind either way, knowing would just let me get organized. :)

2019-07-17 13:22 UTC, gvallee commented
I had the green light from everyone during a meeting so I am merging the PR.

2019-07-17 13:22 UTC, merged