Fakeroot feature documentation
apptainer/singularity-userdocs pull request #200
Opened 2019-07-02 12:00 UTC by cclerget

## This fixes or addresses the following GitHub issues:

- Fixes #126

2019-07-02 14:12 UTC, jchavezlavalle requested changes
some small suggestions :+1: thanks @cclerget this was clearly needed

2019-07-02 14:12 UTC, devprincess commented on fakeroot.rst
> +Fakeroot feature (or commonly referred as rootless mode) allow an unprivileged user
allow -> allows

2019-07-02 14:12 UTC, devprincess commented on fakeroot.rst
> +and the **requested namespaces**, which means this user:
which means **that** this user

2019-07-02 14:12 UTC, devprincess commented on fakeroot.rst
> +have already access or rights on host filesystem, so a **"fake root"** user won't be able
on **the** host filesystem

2019-07-02 14:12 UTC, devprincess commented on fakeroot.rst
> +Additionally all files or directories created with **"fake root"** user are owned like
add comma after "Additionally"

2019-07-02 14:12 UTC, devprincess commented on fakeroot.rst
> +Let's take an example, `user` is authorized to use the fakeroot feature and can use 65536
Let's see the following example, in this case "user" is authorized ....

2019-07-02 14:12 UTC, devprincess commented on fakeroot.rst
> +Which means if **"fake root"** user create a file a ``bin`` user in container, this file will
create -> creates

2019-07-02 14:12 UTC, devprincess commented on fakeroot.rst
> +be owned by ``131073:131073`` outside of container. This is the responsibility of administrator to
The responsibility relies on the administrator to ensure that there is no overlap with the current user's UID/GID on the system.

2019-07-02 14:12 UTC, devprincess commented on fakeroot.rst
> +Restriction are also applied for network, if ``singularity`` is executed without ``--net`` flag,
Restriction -> Restrictions

2019-07-02 14:12 UTC, devprincess commented on fakeroot.rst
> +With ``--net`` the **"fake root"** user have full privileges in this dedicated network, inside
the "fake root" user **has** full privileges..

2019-07-02 14:12 UTC, devprincess commented on fakeroot.rst
> +container network he can bind  on privileged ports below 1024, use ping, manage firewall rules,
inside **the** container network he can bind on privileged ports below 1024.. (remove the space between word "bind" and "on")

2019-07-02 14:12 UTC, devprincess commented on fakeroot.rst
> +listen trafic ...
**traffic**

2019-07-02 14:12 UTC, devprincess commented on fakeroot.rst
> +With fakeroot a unprivileged user can now build image from a definition file with few restrictions, bootstrap
**an** unprivileged user

2019-07-02 14:48 UTC, cclerget commented
Fixed. Thanks for the correction/suggestions @devprincess :+1:

2019-07-02 16:18 UTC, rherban commented
This also fixes sylabs/singularity #3752

2019-07-05 16:52 UTC, jchavezlavalle approved these changes

2019-07-05 16:52 UTC, merged