Bootstrap Agents and %sections updated
apptainer/singularity-userdocs pull request #202
Opened 2019-07-03 20:46 UTC by sushma-4

## Description of the Pull Request (PR):

This PR includes documentation on Bootstrap agents introduced after v3.0
Also now the description of %sections on the page is shuffled to be in the order of their execution during build process.

## This fixes or addresses the following GitHub issues:

- Fixes #93 #184

2019-07-05 17:12 UTC, jchavezlavalle requested changes
some suggestions, feel free to ping me if anything is not clear @sushma-4 thank you!

2019-07-05 17:12 UTC, jchavezlavalle commented on .circleci/config.yml
> +      - image: circleci/python:3.6-stretch
maybe we should also consider the same python version as the one on the readme? 2.7? https://github.com/sylabs/singularity-userdocs#i-want-to-contribute-how-can-i-set-up-my-environment

2019-07-05 17:12 UTC, jchavezlavalle commented on .circleci/config.yml
> +            make html SKIPCLI=1
it would be nice to have a git clone from singularity into `/vendor/src/github.com/sylabs/` and then a `make html` after with no skipcli flag on, also `make epub` and `make latexpdf` commands are missing

2019-07-05 17:12 UTC, devprincess commented on appendix.rst
> +.. _docker-daemon-archive:
could you add these changes on a separate PR? looks like you're adding the CI stuff and also updating a section am I correct? thanks!

2019-07-05 17:12 UTC, devprincess commented on appendix.rst
> +The From keyword is mandatory and applies to these modules in the same nature
add `` to "From"

2019-07-05 17:12 UTC, devprincess commented on appendix.rst
> +over a base(parent) image pulled from either Library/Docker/Shub etc, but
how about Oras?

2019-07-05 17:12 UTC, devprincess commented on appendix.rst
> +This module allows you to take full control of the content inside your container,
The bootstrap agent module allows you to...

2019-07-05 17:12 UTC, devprincess commented on appendix.rst
> +container. The installation of any software, necessary config files can all be
necessary configuration files

2019-07-05 17:12 UTC, devprincess commented on appendix.rst
> +mentioned in the ``%setup`` section of the definition file. This agent is
here saying "This agent" is correct since you already started by mentioning it at the very beginning of the paragraph :+1:

2019-07-05 17:12 UTC, devprincess commented on appendix.rst
> +particularly useful for creating minimal image sizes and are more secure since
and "is" more secure (if what you're talking about is the agent)

2019-07-05 17:12 UTC, devprincess commented on appendix.rst
> +attack surface.
attack surface is repeated twice here

2019-07-05 17:12 UTC, devprincess commented on appendix.rst
> +does not support any keywords.
it does not require what?

2019-07-05 17:12 UTC, devprincess commented on definition_files.rst
> +them and see examples in the :ref:`appendix <buildmodules>`:
add the word "section" so it can be read: in the appendix section.

2019-07-05 17:12 UTC, devprincess commented on definition_files.rst
> +This is where you will download files from the internet with tools like ``git``
This section is where you can download files ...

2019-07-05 17:12 UTC, devprincess commented on definition_files.rst
> +Consider the example from the definition file above:
from the following definition file **below**:

2019-07-05 17:12 UTC, devprincess commented on definition_files.rst
> +Singularity 3.2 introduces multi-stage builds where one environment can be used
Are all these changes related to 3.2? if so, please update the branch to where this PR Is intended to go to.. otherwise pull the version from the variable declared on the replacements python script :+1:

2019-07-08 19:58 UTC, sushma-4 commented on definition_files.rst
> +Singularity 3.2 introduces multi-stage builds where one environment can be used
I meant starting from version 3.2 sorry

2019-07-08 19:59 UTC, sushma-4 commented on definition_files.rst
> +Consider the example from the definition file above:
I'm refering to the def file written at line 134

2019-07-08 20:00 UTC, sushma-4 commented on appendix.rst
> +does not support any keywords.
keywords.. like read it in one go.. does not make sense, I can sure reframe

2019-07-08 20:03 UTC, sushma-4 commented on appendix.rst
> +This module allows you to take full control of the content inside your container,
This is for consistency, all the other sections were having bootstrap in the heading and were being called modules in description, so I kept them the same way.

2019-07-08 20:04 UTC, sushma-4 commented on appendix.rst
> +.. _docker-daemon-archive:
Yes, this indeed is messed up. I'm trying to fix asap

2019-07-09 10:02 UTC, sushma-4 commented
Reopening this in a New PR

2019-07-09 10:02 UTC, closed without merging