Updated labels section example -> 3.2
apptainer/singularity-userdocs pull request #207
Opened 2019-07-08 19:09 UTC by devprincess

This fixes or addresses the following GitHub issues:

- Fixes #205

2019-07-08 20:04 UTC, ikaneshiro approved these changes
lgtm!

2019-07-09 07:00 UTC, Flamefire commented on definition_files.rst
> +Note that labels are defined by a key-value pair and are delimited by a space character.
Shouldn't it be "labels are defined by a key-value pair**s**"?

To even more highlight how this works, could you add `MyLabel Hello World` and  "the **last** ~~variable~~ label name is ``MyLabel``` with a value of ``Hello World``."

This would nicely show that it is split on the FIRST space and spaces in the value are allowed. And removes the "variable" (I guess accidentally added)

2019-07-09 07:45 UTC, devprincess commented on definition_files.rst
> +Note that labels are defined by a key-value pair and are delimited by a space character.
that's a good example, thanks, working on it :+1:

2019-07-09 08:44 UTC, Flamefire requested changes

2019-07-09 08:44 UTC, Flamefire commented on definition_files.rst
> +Note that labels are defined by a key-value pairs and are delimited by the first space character.
remove "a".

And I was first confused about the "delimited by the first space character.". Does this mean key-value? One label from the next? But can't think of a better wording

2019-07-09 08:44 UTC, Flamefire commented on definition_files.rst
> +        MyLabel Hello World
Add this to the example output below

2019-07-09 09:17 UTC, Flamefire approved these changes

2019-07-09 11:09 UTC, merged