Added Container Security page
apptainer/singularity-userdocs pull request #219
Opened 2019-07-22 18:17 UTC by sushma-4

## Description of the Pull Request (PR):

Describes different methods Singularity uses to achieve Security.

2019-07-24 14:50 UTC, jchavezlavalle requested changes
added some comments around @sushma-4 thanks!

2019-07-24 14:50 UTC, devprincess commented on security.rst
> +Containers are all rage today for many good reasons. They are light in weight, easy to spinup and  require less system resources
remove additional space after "easy to spinup and.."

2019-07-24 14:50 UTC, devprincess commented on security.rst
> +core missions of containers - Mobility of Compute, Reproducibility, HPC support, and **Security**. This document intends to aware
replace - to :

2019-07-24 14:50 UTC, devprincess commented on security.rst
> +users of different approaches Singularity takes in offering security features.
This document intends to aware users of different approaches about security features supported by Singularity.

2019-07-24 14:50 UTC, devprincess commented on security.rst
> +feature by creating and managing PGP keys with Singularity. After building an image within Singularity, user can ``signularity sign``
typo on `singularity sign`

2019-07-24 14:50 UTC, devprincess commented on security.rst
> +the container and push it to the Library along with its public PGP key(Stored in :ref:`Keystore <keystore>`) which later can be
would it be a good idea to mention before a bit about PGP and link the website to the OpenPGP site?

2019-07-24 14:50 UTC, devprincess commented on security.rst
> +Singularity to provide a guide. At runtime, the ``--apply-cgroups`` option is used to specifiy the location of the configuration
typo on "specify"

2019-07-24 14:50 UTC, devprincess commented on security.rst
> +``--securtity`` options
typo on `--security`

2019-07-24 14:50 UTC, devprincess commented on security.rst
> +service is based on the OpenPGP HTTP Keyserver Protocol (HKP), with several enhancements:
add some ref to the OpenPGP site as well here

2019-07-24 14:50 UTC, devprincess commented on security.rst
> +
remove added lines at the end

2019-07-25 12:37 UTC, jchavezlavalle approved these changes

2019-07-25 14:42 UTC, gregwkeller approved these changes

2019-07-25 14:42 UTC, gregwkeller commented on security.rst
> +Containers are all rage today for many good reasons. They are light in weight, easy to spinup and  require less system resources
all the rage

2019-07-25 14:42 UTC, gregwkeller commented on security.rst
> +Containers are all rage today for many good reasons. They are light in weight, easy to spin-up and require less system resources
"all the rage" is the expression intended here.  
"light in weight" should be "light weight" or eliminated since it's redundant to "...require less system resources"

2019-07-25 14:42 UTC, gregwkeller commented on security.rst
> +core missions of containers : Mobility of Compute, Reproducibility, HPC support, and **Security**. This document intends to aware
Change aware to inform

2019-07-25 14:42 UTC, gregwkeller commented on security.rst
> +promotes collaboration within and between teams at work.
Consider replacing promotes with protects.  
Consider replacing "teams at work" with "systems and teams"

2019-07-25 14:42 UTC, gregwkeller commented on security.rst
> +container files. Since it is all encrypted, it can defend intruders from getting hold of the image while in transit and manipulating
"can defend from Intruders manipulating the image while in transit.

2019-07-25 15:46 UTC, merged