Added encrypted containers documentation
apptainer/singularity-userdocs pull request #231
Opened 2019-08-19 22:39 UTC by schebro

## Description of the Pull Request (PR):

Added documentation for encrypted containers

## This fixes or addresses the following GitHub issues:

- Fixes #

2019-08-26 17:08 UTC, ikaneshiro requested changes

2019-08-26 17:08 UTC, ikaneshiro commented on encryption.rst
> +Users can build a secure container environment by encrypting the root file
Maybe include the word `confidential` in the description? Because secure wrt containers usually covers a lot of aspects that this does not address

2019-08-26 17:08 UTC, ikaneshiro commented on encryption.rst
> +Privacy Enhanced Mail (PEM) file and a matching private RSA key.  The container
maybe instead:
`via a RSA key pair in Privacy Enhanced Mail (PEM) formatted files.`

2019-08-26 17:08 UTC, ikaneshiro commented on encryption.rst
> +        Passphrase encryption is less secure the encrypting containers using a
```suggestion
        Passphrase encryption is less secure than encrypting containers using a 
```

2019-08-26 17:08 UTC, ikaneshiro commented on encryption.rst
> +        PEM file and private RSA key (detailed below).  Passphrase encryption is
you can probably just say "RSA key pair" here

2019-08-26 17:08 UTC, ikaneshiro commented on encryption.rst
> +        encrypted containers in production are encouraged to use a PEM key.
```suggestion
        encrypted containers in production are encouraged to use asymmetric keys.   
```

2019-08-26 17:08 UTC, ikaneshiro commented on encryption.rst
> +In this case it is necessary to use the ``--encrypted`` flag since the presence
```suggestion
In this case it is necessary to use the ``--encrypt`` flag since the presence
```

2019-08-26 17:08 UTC, ikaneshiro commented on encryption.rst
> +In this case it is necessary to use the ``--encrypted`` flag since the presence
```suggestion
In this case it is necessary to use the ``--encrypt`` flag since the presence
```

2019-08-26 17:08 UTC, ikaneshiro commented on encryption.rst
> +To ``run``, ``shell``, or ``exec`` an encrypted image, the same credentials used
Not necessarily the same credentials in the asymmetric key case. Maybe just say "credentials to decrypt the image need to be supplied at runtime, either ..."

2019-08-29 03:40 UTC, gvallee commented
I tested the directions for the encryption/decryption with a PEM file and the `run` command always fails:
```
FATAL:   Cannot retrieve key from image /tmp/rsa/encrypted.sif: asn1: structure error: tags don't match (16 vs {class:1 tag:15 length:112 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pkcs1PrivateKey @2
loading private key for key decryption
github.com/sylabs/singularity/pkg/util/crypt.PlaintextKey
    pkg/util/crypt/key.go:104
github.com/sylabs/singularity/cmd/internal/cli.execStarter
    cmd/internal/cli/actions_linux.go:284
github.com/sylabs/singularity/cmd/internal/cli.glob..func3
    cmd/internal/cli/actions.go:450
github.com/spf13/cobra.(*Command).execute
    vendor/github.com/spf13/cobra/command.go:830
github.com/spf13/cobra.(*Command).ExecuteC
    vendor/github.com/spf13/cobra/command.go:914
github.com/sylabs/singularity/cmd/internal/cli.ExecuteSingularity
    cmd/internal/cli/singularity.go:246
main.main
    cmd/singularity/cli.go:17
runtime.main
    /usr/local/go/src/runtime/proc.go:201
runtime.goexit
    /usr/local/go/src/runtime/asm_amd64.s:1333
```

But if I use the same command with a pair of keys generated by the e2e test, it works. So I believe the documentation for the generation of the PEM files is incorrect.

2019-08-29 16:09 UTC, ikaneshiro requested changes
Lets add a small note around the container building portions that the definition used to build the container will be stored in plaintext within the sif and that this can be removed using the `siftool`. Also small nitpick

2019-08-29 16:09 UTC, ikaneshiro commented on encryption.rst
> +RSA key pair in Privacy Enhanced Mail (PEM) format and a matching private RSA
Dont need `and a matching private RSA key.` at the end of this sentence

2019-09-13 16:36 UTC, dctrud commented
It doesn't look like I can push further changes into @schebro 's branch so I'll open a new PR in a personal branch but be sure to maintain the commits and credit to @schebro

2019-09-16 12:23 UTC, merged