Network page
apptainer/singularity-userdocs pull request #24
Opened 2018-10-16 14:57 UTC by GodloveD

2018-10-16 15:37 UTC, jchavezlavalle requested changes

2018-10-16 15:37 UTC, devprincess commented on networking.rst
> +make network virtualisation easy.
Change `virtualisation` to `virtualization`

2018-10-16 15:37 UTC, devprincess commented on networking.rst
> +network namespace when it initiates.  New in Singularity 3.0, a bridge
double word `network` here

2018-10-16 15:37 UTC, devprincess commented on networking.rst
> +bring up a dedicated interface inside container.
Additional space between `Each` and `entry`

2018-10-16 15:41 UTC, jchavezlavalle requested changes

2018-10-16 15:41 UTC, devprincess commented on networking.rst
> +bring up a dedicated interface inside container.
Maybe this section for `--network` flag should be just right after `--net` since they are related ?

2018-10-16 21:16 UTC, GodloveD commented on networking.rst
> +bring up a dedicated interface inside container.
I'm not sure about this.  The `--network-args` option is also related in the sense that it doesn't function properly without the `--net` flag.  I basically just promoted the `--net` flag to the top of the list since it was present in 2.x and then alphabetized everything else.  Maybe it's best to just alphabetize them?

2018-10-17 07:27 UTC, jchavezlavalle commented on networking.rst
> +bring up a dedicated interface inside container.
yes, good idea :+1: thanks @GodloveD

2018-10-17 12:54 UTC, cclerget approved these changes
Looks good to me !

2018-10-17 20:12 UTC, jchavezlavalle approved these changes

2018-10-17 20:12 UTC, merged