added bind path documentation
apptainer/singularity-userdocs pull request #25
Opened 2018-10-18 03:32 UTC by GodloveD

had to be changed up a lot b/c of our new underlay strategy

2018-10-18 06:43 UTC, cclerget requested changes
Just a small addition for me but overall looks good Dave !

2018-10-18 06:43 UTC, cclerget commented on bind_paths_and_mounts.rst
> +Many of the Singularity commands such as ``run``, ``exec`` , and ``shell`` will
maybe add `instance start`

2018-10-19 21:14 UTC, GodloveD commented
Sorry it took me so long to push changes @cclerget and @devprincess .  Evidently I pushed on the wrong branch by mistake.

2018-10-19 21:19 UTC, cclerget approved these changes

2018-10-20 10:13 UTC, merged