Installation
apptainer/singularity-userdocs pull request #33
Opened 2018-11-29 04:57 UTC by GodloveD

Now you know what I've been doing for the last 2 days.  Whew!  

@yhcote it would be really great if you could go over the `mconfig` bits and keep me honest!

Thank you!

2018-11-29 07:22 UTC, jmstover requested changes

2018-11-29 07:22 UTC, jmstover commented on installation.rst
> +    $ export VERSION=3.0.1 # adjust this as necessary && \
This won't work for copy paste. Change to:
```
$ export VERSION=3.0.1 && # adjust this as necessary \
```

2018-11-29 07:22 UTC, jmstover commented on installation.rst
> +        /usr/local/bin/singularity \
You don't have the `run-singularity` script

2018-11-29 14:26 UTC, GodloveD commented on installation.rst
> +    $ export VERSION=3.0.1 # adjust this as necessary && \
In my hands it works just fine. (I double checked b/c I also had doubts.) But maybe it doesn't work on old crusty SlackWear or whatever so I'm happy to change. 

😂

2018-11-29 14:28 UTC, GodloveD commented on installation.rst
> +        /usr/local/bin/singularity \
So that means that it's not being listed by `sudo make install`.  meh.  Wonder what else is being silently installed.  😞

2018-11-29 14:34 UTC, GodloveD commented on installation.rst
> +        /usr/local/bin/singularity \
Do you think I should address this by just instructing users to delete all of the parent directories that are created during installation?

2018-11-29 15:59 UTC, jmstover commented on installation.rst
> +        /usr/local/bin/singularity \
I just saw that it's there... the list is out of order. If you just copy pasted that makes sense though. ;)

You an remove all of:
  `/usr/local/libexec/singularity`
  `/usr/local/etc/singularity`

But having a removal of `/usr/local/bin` ... not so much. ;P

2018-11-29 16:01 UTC, jmstover commented on installation.rst
> +    $ export VERSION=3.0.1 # adjust this as necessary && \
If that works ... they changed behavior of comments. I don't like that...   I mean, you're commenting out the `\` ...

2018-11-29 18:48 UTC, jchavezlavalle requested changes
some typos to check here @GodloveD, thanks! :+1:

2018-11-29 18:48 UTC, devprincess commented on installation.rst
> +    Packaged versions of Singularity in Linux distrubution repos are maintained
There's a typo in "distribution" on line 294 here

2018-11-29 18:48 UTC, devprincess commented on installation.rst
> +backports for older Debian and Ubuntu releases, it is recommend that you use the
"...and Ubuntu releases, it is **recommended**..."

2018-11-29 18:48 UTC, devprincess commented on installation.rst
> +The epel (Extra Packages for Enterprise Linux) repos contains Singularity. The
The epel repos **contain** Singularity

2018-11-29 18:48 UTC, devprincess commented on installation.rst
> +    Dear shared resource admininstrator,
Dear shared resource **administrator**

2018-11-29 19:36 UTC, GodloveD commented on installation.rst
> +        /usr/local/bin/singularity \
I don't think the `make man` command is even working in the 3.0.1 version of Singularity so I'm going to omit telling folks to remove man pages for now.

2018-11-29 19:45 UTC, GodloveD commented on installation.rst
> +        /usr/local/bin/singularity \
@jmstover plz resolve this convo if you are happy.

2018-11-29 19:45 UTC, jmstover commented on installation.rst
> +        /usr/local/bin/singularity \
It works ... if you build the RPM you have the man pages. 

If you change `_prefix` it breaks, but there was a fix in for that.

2018-11-29 19:48 UTC, jmstover commented on installation.rst
> +        /usr/local/bin/singularity \
The bash completion will be at:  `/usr/local/etc/bash_completion.d/singularity` . It gets installed to `$(SYSCONFDIR)/bash_completion.d` ... and a `--prefix=/usr/local` makes that value:  `/usr/local/etc`

2018-11-29 19:55 UTC, GodloveD commented on installation.rst
> +        /usr/local/bin/singularity \
Well, this procedure is not for an RPM installation right?  Because then you would just use `rpm -e`

The only reason you would be manually deleting files is if you ran `make install` yourself.  And like I said, `make man` is busted right now.  

Also, as far as the bash completion file, I'm explicitly telling users to copy it to `/etc/bash_completion.d/singularity` so that it will work.

https://github.com/sylabs/singularity-userdocs/blob/df148635d5cf1ce6c3c66d0e7b59b5b04c8027d6/installation.rst#copy-bash-completion-file

Maybe that is why bash completion doesn't work by default with an rpm installation.

2018-11-29 20:05 UTC, jmstover commented on installation.rst
> +        /usr/local/bin/singularity \
That's still going to leave the one that's installed under:  `/usr/local/etc/bash_completion.d` though...

2018-11-30 01:26 UTC, GodloveD commented on installation.rst
> +        /usr/local/bin/singularity \
Jeez.  I didn't even know that `make install` put a copy there.  Why does it do so?  It's basically useless there.  It's not like it will make bash completion work in that directory.

2018-11-30 06:47 UTC, jmstover commented on installation.rst
> +        /usr/local/bin/singularity \
Just not automatically ... if you source it, then it still works fine.

2018-11-30 14:52 UTC, GodloveD commented on installation.rst
> +        /usr/local/bin/singularity \
Well, the `singularity` binary would also work if we put it in `/usr/local/bin/singularity/singularity` or some other silly path if we just told users to adjust their `$PATH` but that is obviously quite ridiculous. 

I'm going to change the instructions that I provide so that I'm advising users to source `/usr/local/etc/bash_completion.d/singularity` and to put that change in their `.bashrc`.  But I'm also going to open an issue and advocate that we start doing something more sane with the bash completion file.  This is pretty silly.

2018-11-30 15:43 UTC, jmstover commented on installation.rst
> +        /usr/local/bin/singularity \
No... It comes down to the value of `SYSCONFDIR`. If you want it to be system wide, you need to specify a system wide value for that. But that same location also controls where the `singularity.conf` ends up. So, if you want system wide to work out of the box, do something like:

```
./mconfig --prefix=/usr/local --sysconfdir=/etc
```

2018-11-30 16:12 UTC, GodloveD commented on installation.rst
> +        /usr/local/bin/singularity \
OK.  Check my latest commit and see if it works better with the current state of things.

2018-11-30 17:35 UTC, jmstover commented on installation.rst
> +        /usr/local/bin/singularity \
:+1:

2018-11-30 17:36 UTC, jmstover approved these changes

2018-11-30 20:26 UTC, kmanalo commented
@GodloveD I was actually looking for this content, so thanks for your great timing

2018-12-03 20:00 UTC, jchavezlavalle approved these changes
lgtm! @GodloveD

2018-12-03 20:04 UTC, merged

2018-12-03 20:27 UTC, GodloveD commented
Thank you!