Add definition file instructions
apptainer/singularity-userdocs pull request #35
Opened 2018-12-08 03:53 UTC by GodloveD

Another big ole nasty review!  😜

2018-12-10 18:29 UTC, jchavezlavalle requested changes

2018-12-10 18:29 UTC, jchavezlavalle commented on appendix.rst
> +The Library keyword is optional. It will default to `` https://library.sylabs.io``.
Shouldn't this url be ``https://cloud.sylabs.io/library`` ?

2018-12-10 18:36 UTC, jmstover requested changes

2018-12-10 18:36 UTC, jmstover commented on appendix.rst
> +You can use an existing container on the Container Library your “base,” and then
```
as your "base,"
```

2018-12-10 18:36 UTC, jmstover commented on appendix.rst
> +    From: <entity>/<collection>/<container>:<tag>
Is this still the current layout? I know it's being changed....   @tri-adam

2018-12-10 20:32 UTC, jchavezlavalle requested changes

2018-12-10 20:32 UTC, devprincess commented on definition_files.rst
> +    Stopping instance1 instance of /home/vagrant/my_container.sif (PID=19035)
I guess it should be  ``(PID=19061)`` ?

2018-12-10 20:32 UTC, devprincess commented on definition_files.rst
> +Running the test command on a container built with this def file yeilds the
"..with this def file **yields** the following:"

2018-12-10 20:32 UTC, devprincess commented on definition_files.rst
> +Best Practices for Build Recipes
Best Practices for **Building** Recipes?

2018-12-10 21:29 UTC, jmstover commented on definition_files.rst
> +Best Practices for Build Recipes
I think "Build Recipes" works in this context.

2018-12-10 21:31 UTC, jmstover commented on definition_files.rst
> +    Stopping instance1 instance of /home/vagrant/my_container.sif (PID=19035)
No ... 19035 should be the process of the parent instance process, where 19061 is the PID of a process running from within the instance.

2018-12-12 02:48 UTC, ikaneshiro requested changes

2018-12-12 02:48 UTC, ikaneshiro commented on definition_files.rst
> +    of the container on the host system itself, and is executed will elevated
with?

2018-12-12 02:48 UTC, ikaneshiro commented on definition_files.rst
> +pair of ``<source>`` and ``<destination>``, where the source is a path on your
How about:
Each line is a ``<source>`` and ``<destination>`` pair, ...

2018-12-12 02:48 UTC, ikaneshiro commented on definition_files.rst
> +Running the container built using this def file will yeild the following:
yield

2018-12-12 02:48 UTC, ikaneshiro commented on appendix.rst
> +container from a mirror URI.
We reference uri's throughout this doc when talking about things related to `MirrorURL`. Should we change these to `URL` and leave `URI` for things like `docker`, `shub` and `library`?

2018-12-13 01:46 UTC, GodloveD commented on appendix.rst
> +    From: <entity>/<collection>/<container>:<tag>
It's the layout as of now.  We will need to change when it changes (and matching changes have been made and merged and released in Singularity.)

2018-12-13 02:07 UTC, GodloveD commented on appendix.rst
> +container from a mirror URI.
I'm actually not sure when to say URI and URL.  It's my understanding that if one is in doubt URI is a superset and should be prefered.  Thoughts?

2018-12-13 02:16 UTC, ikaneshiro commented on appendix.rst
> +container from a mirror URI.
I'm pretty sure this counts as a `URL` since it requires `http(s)://`. But you're correct that `URI` is a superset of `URL`, so I think its fine to say that. I'm just suggesting to keep it consistent throughout the page one way or the other. Like if you look at line 280, that section uses `URL` instead of `URI`.

2018-12-13 17:03 UTC, ikaneshiro approved these changes

2018-12-13 18:58 UTC, jchavezlavalle requested changes

2018-12-13 18:58 UTC, devprincess commented on appendix.rst
> +You can use an existing container image as your “base,” and then add
`as your “base”,`

2018-12-13 19:05 UTC, jchavezlavalle requested changes

2018-12-13 19:05 UTC, devprincess commented on definition_files.rst
> +in the def file is uninportant and multiple sections of the same name can be
in the def file is **unimportant** and multiple...

2018-12-13 19:05 UTC, devprincess commented on definition_files.rst
> +scriptlet with elevated priviledges on the host system during the build, it's
with elevated **privileges** on the host system during the build, **its** use is generally discouraged

2018-12-14 13:52 UTC, GodloveD commented on appendix.rst
> +You can use an existing container image as your “base,” and then add
all of your "base," are belong to us

2018-12-14 15:06 UTC, jmstover approved these changes

2018-12-14 16:31 UTC, jchavezlavalle approved these changes

2018-12-17 16:50 UTC, merged