(docs) update bind_paths_and_mounts.rst
apptainer/singularity-userdocs pull request #390
Opened 2021-04-16 09:05 UTC by vladdoster

## Description of the Pull Request (PR):

- spelling
- reduce verbiage
- fix punctuation

## This fixes or addresses the following GitHub issues:

N/A

2021-04-19 14:48 UTC, dtrudg requested changes

2021-04-19 14:48 UTC, dtrudg commented on bind_paths_and_mounts.rst
> +Using the environment variable instead of the command line argument, would
The `this` should not be removed.

2021-04-19 14:48 UTC, dtrudg commented on bind_paths_and_mounts.rst
> +In Singularity 3.6 and above, you can mount a directory contained in an
comma shouldn't be added, the statement is directly about Singualrity 3.6 and above.

2021-04-19 14:48 UTC, dtrudg commented on bind_paths_and_mounts.rst
> +to distribute in a read-only image file, and compressed, then
Please leave original text, which specifies the image file itself is read-only and compressed.

Suggested change is not specific that the image file provides the compression.

2021-04-19 14:48 UTC, dtrudg commented on bind_paths_and_mounts.rst
> +If your bind source is a SIF, then Singularity will bind from
Comma not needed here. Better overall would be split into to sentences without adding a comma.

> If your bind source is a SIF then Singularity will bind from the first data partition in the SIF. You may specify an alternative descriptor by ID with the additional bind option ...

2021-05-26 06:02 UTC, brianclemens commented
Closed for inactivity.

2021-05-26 06:02 UTC, closed without merging