Update appendix.rst
apptainer/singularity-userdocs pull request #393
Opened 2021-04-17 04:21 UTC by vladdoster

## Description of the Pull Request (PR):

Corrects the following:
- grammar
- spelling
- split infinitives
- punctuation

## This fixes or addresses the following GitHub issues:

N/A

2021-04-19 14:41 UTC, dtrudg requested changes
Thank you for the contribution! I agree with most of the changes here, but not all, and if text was previously wrapped <80 columns this should be maintained.

2021-04-19 14:41 UTC, dtrudg commented on appendix.rst
> +The Fingerprints keyword is optional. It specifies one or more comma-separated fingerprints corresponding to PGP public keys. If present,
If the existing text is hard wrapped, please ensure changes are hard-wrapped, and are not long lines.

2021-04-19 14:41 UTC, dtrudg commented on appendix.rst
> +essentials such that the ``%post`` section has what it needs to complete the build properly.
If the existing text is hard wrapped, please ensure changes are hard-wrapped, and are not long lines.

2021-04-19 14:41 UTC, dtrudg commented on appendix.rst
> +The scratch bootstrap agent allows you to start from an empty container. You are then responsible for adding any
The `completely empty` and 'any and all' in the original text here are valid to emphasize the nature of a scratch container and do not need to be removed.

2021-05-26 06:03 UTC, brianclemens commented
Closed for inactivity.

2021-05-26 06:03 UTC, closed without merging