Fix singularity docs refs
apptainer/singularity-userdocs pull request #402
Opened 2021-06-29 02:44 UTC by pedroalvesbatista

## Description of the Pull Request (PR):
Updates references to user-docs links that before pointed to Sylabs links.

## This fixes or addresses the following GitHub issues:
No issues refs to here.

**Before submitting a PR, make sure you have done the following:**

* Read the [Guidelines for Contributing](https://github.com/hpcng/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
* Added changes to the CHANGELOG if necessary according to the [Contribution Guidelines](https://github.com/hpcng/singularity/blob/master/CONTRIBUTING.md)
* Added tests to validate this PR and tested this PR locally with a `make testall`
* Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/hpcng/singularity/blob/master/CONTRIBUTING.md)
* Added myself as a contributor to the [Contributors File](https://github.com/hpcng/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

2021-06-29 16:11 UTC, DrDaveD requested changes
Looks good after you accept my suggested minor wording changes.

2021-06-29 16:11 UTC, DrDaveD commented on contributing.rst
> +security  related issue/problem, please email Singularity Project Team directly at
```suggestion
security  related issue/problem, please email the Singularity Security Team directly at 
```

2021-06-29 16:11 UTC, DrDaveD commented on security.rst
> +would with any other software. Singularity Community is constantly probing to find
```suggestion
would with any other software. The Singularity community is constantly probing to find
```

2021-06-29 16:11 UTC, DrDaveD commented on security.rst
> +public disclosure, as detailed in the `Singularity Community Security Policy
```suggestion
public disclosure, as detailed in the `Singularity Security Policy
```

2021-06-29 19:47 UTC, pedroalvesbatista commented
Closed accidentally

2021-06-30 17:14 UTC, DrDaveD approved these changes

2021-06-30 17:14 UTC, merged