Added Contributing to 3.0
apptainer/singularity-userdocs pull request #44
Opened 2018-12-17 20:42 UTC by WestleyK

Not much changed from 2.X. mostly copy-paste :smile: 

This PR will fix/close:

  - Fixes #36

2018-12-18 17:05 UTC, GodloveD requested changes
I would add a section on raising issues and a link to how to do that.  In that section I would also explain that if you have found a security-related bug you should email security@sylabs.io instead.  I would put the contributing to the docs section above the section about contributing to the source code.  I would also substantially condense the sections that talk about how to use git.  There is a lot of opinionated advice on the best way to use git that seems out of place.  This should be a guide on how the contribute to Singularity and not a guide on how to use git imho, though a few pointers would not be a bad thing.

2018-12-18 17:05 UTC, GodloveD commented on contributing.rst
> +I usually open it up right after cloning my fork to add the repository that I forked as a `remote <https://help.github.com/articles/adding-a-remote/>`_, so I can easily get updated from it.
The way this is written encourages a user to edit `.git/config`.  This is a pretty dangerous thing to suggest imho and it has screwed me up before.  I think that we should actually point users to the `git remote add upstream` command instead and then just tell them to check that the appropriate changes have been made on their behalf in the `.git/config` file.

2018-12-18 17:05 UTC, GodloveD commented on contributing.rst
> +
please remove the redundant blank lines.

2018-12-18 17:05 UTC, GodloveD commented on contributing.rst
> +In the GitHub flow, the master branch is the frozen, current version of the software.
We no longer use GitHub flow and the master branch is not frozen.  So these instructions need to be updated.  Check this:

https://www.sylabs.io/2018/03/managing-singularity-branches/

2018-12-18 17:05 UTC, GodloveD commented on contributing.rst
> +`Branches <https://guides.github.com/introduction/flow//>`_ are a way of isolating your features. For example, if I am working on several features, I would want to keep them separate, and “submit the
This is really verbose.  We can probably say what we need to say here without giving everyone a tutorial of GitHub.

2018-12-18 17:05 UTC, GodloveD commented on contributing.rst
> +    git commit -a
Using the `-a` option is actually a pretty poor practice imho.  Especially when it comes to docs.  If you have used the `make html` command there will be a bunch of new files in the `_build` directory that you actually don't want to add.  Much better to explicitly use the `git add file1 file2` command and control what you want to stage for commit and then do a `git commit -m "my message"`

2018-12-18 17:05 UTC, GodloveD commented on contributing.rst
> +This will open up a little window in your default text editor that you can write a message in the first line. This commit message is important - it should describe exactly the changes that you have m
Using the -m option you can avoid messing around with the little window (which is a pain).

2018-12-18 17:05 UTC, GodloveD commented on contributing.rst
> +    git push origin add/my-awesome-feature
I would remove the `add/` here.  I think it's pretty confusing to work with branches as though they were grouped in subdirectories and I don't want to encourage new users to do that.

2018-12-18 18:14 UTC, jchavezlavalle requested changes
@WestleyK some comments around here :+1:

2018-12-18 18:14 UTC, jchavezlavalle commented on contributing.rst
> +-  `Contribute docs <#contributing-to-documentation>`_
these 2 sections need to be referenced below (otherwise those would be dead links when passing to html) , adding a `.. _contribute-to-the-code:` and `.. _contributing-to-documentation:` right before each section title will do it :+1:

2018-12-18 18:14 UTC, devprincess commented on contributing.rst
> +To contribute to the web based documentation, you should obtain a GitHub account and fork the `Singularity <https://github.com/sylabs/singularity>`_ repository.
This is not correct, it should say.. `to contribute to Singularity,` (and not the web based documentation) web based documentation and Singularity have different repos..

2018-12-19 21:07 UTC, WestleyK commented
Okay guys, have another look when you get a chance.

I don't know why Github thinks ` contributing.rst` has conflict. I'm soooo tired of git :angry:

2018-12-20 04:32 UTC, jchavezlavalle reviewed
more comments! @WestleyK

2018-12-20 04:32 UTC, jchavezlavalle commented on contributing.rst
> +Now, we need to checkout are branch, more-content...
we need to checkout **our** branch? Anyway I think maybe what it should say is: "Cloning the repo will bring me an exact copy of the Singularity repository at that moment, but if you may need to update for example the master branch, you will need to follow the next steps:"

2018-12-20 04:32 UTC, devprincess commented on contributing.rst
> +
Between a git checkout and a git pull there should be an update of the upstream branch so doing a git fetch would do the work:
```
git checkout master
git fetch upstream
git pull upstream master
git push origin master
 ```

2018-12-20 04:32 UTC, devprincess commented on contributing.rst
> +    git pull origin development
why would you pull a branch on origin (on your local) that you have just opened?

2018-12-20 04:32 UTC, devprincess commented on contributing.rst
> +    git add file-changed1 files-chenged2
there's a typo on the second file here, also you can add the whole bunch of files with `git add .`

2018-12-20 04:32 UTC, devprincess commented on contributing.rst
> +Note that you should commit changes to the branch you are working on before changing branches, otherwise they would be lost. GitHub will give you a warning and prevent you from changing branches if t
you could add that you can also verify in which branch you're on with `git branch` as well

2018-12-20 04:32 UTC, devprincess commented on contributing.rst
> +
Add the reference `mailto:security@sylabs.io` link here on the security@sylabs.io address

2018-12-20 19:01 UTC, WestleyK commented on contributing.rst
> +    git add file-changed1 files-chenged2
I think Dave said we should avoid `git add -a`, or `git add .`, because there will be lots of files in the `_build/html/` that we don't need. Although maybe `.gitignore` can help with that...

2018-12-20 19:17 UTC, WestleyK commented on contributing.rst
> +    git pull origin development
I did not change any of the `git` commands from `2.X`, I'm hoping you can help out with that and see what needs to be changed. So is the `git pull origin development` not necessary?

2018-12-20 22:41 UTC, jchavezlavalle commented on contributing.rst
> +    git add file-changed1 files-chenged2
_build/html files are already considered in the gitignore

2018-12-20 22:42 UTC, devprincess commented on contributing.rst
> +    git pull origin development
afaik cloning a repo to your local gives you a copy with the same branches so development branch would already be there, no need to pull that branch

2018-12-21 05:31 UTC, GodloveD requested changes
Thanks for working on this @WestleyK!  I'm suggesting another round of edits.

2018-12-21 05:31 UTC, GodloveD commented on index.rst
> +   Contributing <contributing>
Let's move this in between Quick Start and Installation please.

2018-12-21 05:31 UTC, GodloveD commented on contributing.rst
> +-  `Report a Issue <#reporting-a-issue>`_
Please remove the refs here.  There is already a table of contents on the left hand side.  And that one has the benefit that it is automatically generated so we don't have to maintain it.

2018-12-21 05:31 UTC, GodloveD commented on contributing.rst
> +
Add a heading here like 
```
---------------------
Joining the community
---------------------
```
That way the `Singularity Google Group` and `Singularity on Slack` subheadings will appear under an appropriate heading in the TOC on the left

2018-12-21 05:31 UTC, GodloveD commented on contributing.rst
> +This is a huge endeavor, and it is greatly appreciated! If you have been using Singularity and having good luck with it,
This is a huge endeavor, and ~it is~ **your help would be** greatly appreciated!

2018-12-21 05:31 UTC, GodloveD commented on contributing.rst
> +You can contribute to the documentation by sending a `pull request <https://help.github.com/articles/about-pull-requests/>`_ on our repository for documentation.
You can contribute to the documentation by [**raising an issue to suggest an improvement**](https://github.com/sylabs/singularity-userdocs/issues/new) or by sending a...

2018-12-21 05:31 UTC, GodloveD commented on contributing.rst
> +You can contribute to the documentation by sending a `pull request <https://help.github.com/articles/about-pull-requests/>`_ on our repository for documentation.
Please add the appropriate URL to the text "repository for documentation"

2018-12-21 05:31 UTC, GodloveD commented on contributing.rst
> +More information about contributing to the documentation, and the instructions on how to install the dependencies, and how to generate the files can be obtained `here <https://github.com/sylabs/singu
Add a line like...

"For more detailed instructions on making a pull request, see the instructions for [Contributing to the Code](appropriate tag)"

2018-12-21 05:31 UTC, GodloveD commented on contributing.rst
> +We use the traditional `GitHub Flow <https://guides.github.com/introduction/flow/>`_ to develop. This means that you fork the repo and checkout a branch to make changes, you submit a pull request (PR
fork the repo and ~checkout a~ **create a new** branch to make changes

2018-12-21 05:31 UTC, GodloveD commented on contributing.rst
> +We use the traditional `GitHub Flow <https://guides.github.com/introduction/flow/>`_ to develop. This means that you fork the repo and checkout a branch to make changes, you submit a pull request (PR
a pull request (PR) to the ~development~ **master** branch with your changes ~, and the development branch gets merged with master for official releases~.

^ like I said before, you should check out that document with our branch structure.  We don't use a development branch anymore.

2018-12-21 05:31 UTC, GodloveD commented on contributing.rst
> +    cd singularity/
Please follow the conventions in the other files for code blocks.  Change this to...

```
$ git clone https://github.com/your-username/singularity.git \
    cd singularity/
```
In particular, this style keeps a single command on each line to preserve readability, starts with a `$` to indicate that these are commands to be entered into a prompt, and uses the `\` newline syntax so that the whole block can be easily copied and pasted for the lazy (like me).

2018-12-21 05:31 UTC, GodloveD commented on contributing.rst
> +Cloning the repo will bring me an exact copy of the Singularity repository at that moment, but we need to update to the master branch, you will need to follow the next steps:
Cloning the repo will ~bring me~ **create** an exact copy of the Singularity repository at that moment. ~, but we need to~  **In the event that you need to** update ~to the master~ **a** branch, you will need to follow the next steps:

2018-12-21 05:31 UTC, GodloveD commented on contributing.rst
> +    git push origin master
```
$ git remote add upstream https://github.com/sylabs/singularity.git # to add a new remote named "upstream" \
    git checkout master # or another branch to be updated \
    git pull upstream master \
    git push origin master # to update your fork
```
If you are working on a feature branch that needs to be synced with the latest changes in `master` (or another branch) you can do so with:

```
$ git checkout my_feature \
    git merge master
```

2018-12-21 05:31 UTC, GodloveD commented on contributing.rst
> +Cloning the repo will bring me an exact copy of the Singularity repository at that moment, but we need to update to the master branch, you will need to follow the next steps:
On second thought, the bit about updating a branch should be moved to the bottom of the instructions.

2018-12-21 05:31 UTC, GodloveD commented on contributing.rst
> +    git checkout -b development
The `development` branch doesn't exist anymore.  This command and the associated text are out of date.

2018-12-21 05:31 UTC, GodloveD commented on contributing.rst
> +At this point, you can either choose to work on this branch, push to your origin development and pull request to Sylabs development, or you can checkout another branch specific to your feature. We re
Change development to master in this text

2018-12-21 05:31 UTC, GodloveD commented on contributing.rst
> +    git add .
`git add .` is a bad idea.  How about `git add file1 file2 ...`

2018-12-21 05:31 UTC, GodloveD commented on contributing.rst
> +    git push origin my-awesome-feature
plz add `$`

2018-12-21 05:31 UTC, GodloveD commented on contributing.rst
> +    git status
`$` here too

2018-12-21 05:31 UTC, GodloveD commented on contributing.rst
> +submitted to the Sylabs development branch. This will open up a nice conversation interface / forum for the developers of
Sylabs ~development~ **master** branch...

Once again, development does not exist anymore.

2018-12-21 05:31 UTC, GodloveD commented on contributing.rst
> +This is a huge endeavor, and it is greatly appreciated! If you have been using Singularity and having good luck with it, join our `Google Group <https://groups.google.com/a/lbl.gov/forum/#!forum/sing
Please edit this text as it is redundant with text earlier on the page.

2018-12-21 19:59 UTC, WestleyK commented on contributing.rst
> +    git add .
It was like that, but I think @devprincess said to use `.` and `.gitignore` will ignore the `_build/html/`...

2018-12-21 23:47 UTC, WestleyK commented on contributing.rst
> +More information about contributing to the documentation, and the instructions on how to install the dependencies, and how to generate the files can be obtained `here <https://github.com/sylabs/singu
>[Contributing to the Code](appropriate tag)

Umm... what is the appropriate tag? [This one](https://github.com/sylabs/singularity-userdocs/blob/master/README.md#i-want-to-contribute-how-can-i-set-up-my-environment)?
I don't think we have a [`CONTRIBUTING.md`](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md#contributors-agreement) like we do in Singularity...

2018-12-27 03:16 UTC, GodloveD requested changes
Heya @WestleyK.  Thanks for your patience.  Looks like this is getting closer.

2018-12-27 03:16 UTC, GodloveD commented on contributing.rst
> +You can contribute to the documentation by `raising an issue to suggest an improvement <https://github.com/sylabs/singularity-userdocs>`_ or by sending a `pull request <https://github.com/sylabs/sing
Make the links the following:
https://github.com/sylabs/singularity-userdocs/issues/new
https://github.com/sylabs/singularity-userdocs/compare
https://github.com/sylabs/singularity-userdocs

2018-12-27 03:16 UTC, GodloveD commented on contributing.rst
> +Step 3. Checkout a new branch
Steps go directly from Step 1 to Step 3.  Please renumber.

2018-12-27 03:16 UTC, GodloveD commented on contributing.rst
> +Cloning the repo will create an exact copy of the Singularity repository at that moment. in the event that you need to update a master branch, you will need to follow the next steps:
Capitalize the word at the beginning of the sentence and delete the word _master_ in this line.

2018-12-27 03:16 UTC, GodloveD commented on contributing.rst
> +At this point, you can either choose to work on this branch, push to your origin master and pull request to Sylabs master, or you can checkout another branch specific to your feature. We recommend al
These instructions are a bit confusing.  What are you trying to instruct people to do here?

2018-12-27 03:23 UTC, WestleyK commented on contributing.rst
> +You can contribute to the documentation by `raising an issue to suggest an improvement <https://github.com/sylabs/singularity-userdocs>`_ or by sending a `pull request <https://github.com/sylabs/sing
I was hesitant to do this before because, if you were not singed in to github when you click the link, it will bring you to the [login page](https://github.com/login), which could discourage some users that don't have a github account. (maybe I'm overthinking this)

2018-12-27 15:50 UTC, GodloveD commented on contributing.rst
> +You can contribute to the documentation by `raising an issue to suggest an improvement <https://github.com/sylabs/singularity-userdocs>`_ or by sending a `pull request <https://github.com/sylabs/sing
I think it's better to just go to the actual links.

2018-12-27 22:00 UTC, GodloveD approved these changes
I'm happy with the state of this now.  I noticed that it looks like the 2 recent `.md` files are removed by this commit.  Don't know if I did that or if Westley did it.  Will just have to be aware and add them back in if they are deleted from master by this merge.

2018-12-28 15:29 UTC, jchavezlavalle approved these changes

2018-12-28 15:30 UTC, merged