Environment and Metadata section
apptainer/singularity-userdocs pull request #50
Opened 2018-12-21 01:42 UTC by devprincess

Fixes: #37 

Of course since this branch has been checked out from my master branch with the huge previous deletion of files from the _build folder, this PR contains those changes and also the new environment and metadata section updated for 3.0.

2018-12-28 17:57 UTC, jmstover commented on environment_and_metadata.rst
> +to ``$SINGULARITY_ENVIRONMENT`` will end up in the file ``/.singularity.d/env/91-environment.sh``. Of course if no environment variables are exported during the
This ... is worded off. IMO, it should read more like:

```
Of course if nothing is redirected to ``$SINGULARITY_ENVIRONMENT`` in the ``%post`` section, the file ``/.singularity.d/env/91-environment.sh`` will be empty.
```

The `will be empty.` (or `will not exist.`... @GodloveD ?) needs added even if the other part is ignored.

2018-12-28 17:59 UTC, jmstover commented on environment_and_metadata.rst
> +If you need to define a variable at runtime, set variables inside the
`inside the container` .... or `in the running shell` ? Would this be better worded like:

```
If you need to define a variable in the container at runtime, when you execute
singularity pass a variable prefixed with ``SINGULARITYENV_``.
```

2018-12-28 18:01 UTC, jmstover commented on environment_and_metadata.rst
> +
Okay ... here it's just *way* to obvious. 

Do the extra lines in these cause any issues?

2018-12-28 18:01 UTC, jmstover commented on environment_and_metadata.rst
> +-  **env**: All \*.sh files in this directory are sourced in
Do you need to use `\*` here?

2018-12-28 18:03 UTC, jmstover commented on environment_and_metadata.rst
> +   container is invoked with the ``instance.start`` command.
This will be:  `instance start` (not a dot command) for 3.x commands

2018-12-28 21:22 UTC, devprincess commented on environment_and_metadata.rst
> +
yes, when exporting it to html, the file structure created with no lines in between creates some overlapping in the code blocks @jmstover

2018-12-28 21:38 UTC, jmstover commented on environment_and_metadata.rst
> +``%post`` section, the file ``/.singularity.d/env/91-environment.sh``
There's ... something missing here? What needs to go after:
```
the file ``/.singularity.d/env/91-environment.sh``
```

2019-01-03 23:24 UTC, GodloveD requested changes
Heya @devprincess.  I just took a first pass at this and suggested some changes. I think it would probably be a good idea to break this up into 2 seperate PRs actually.  Once you make these changes I'll go back over with a finer-toothed comb.  Thank you.

2019-01-03 23:24 UTC, GodloveD commented on appendix.rst
> +#. **SINGULARITY_ENVIRONMENT**: Contains all the environment variables that have been exported in your container.
This is a good start, but there are many, many more env vars available in Singularity that are not yet covered here.  Might be a good idea to break this off into a seperate PR so that we can get the other page merged.  

Start here to find more env vars:

https://github.com/sylabs/singularity/blob/master/internal/app/singularity/action_flags.go#L84

This line indicates that `SINGULARITY_APP` and `SINGULARITY_APPNAME` are both env vars.  And so on.

2019-01-03 23:24 UTC, GodloveD commented on environment_and_metadata.rst
> +can add to your container during the build process. This page details
Please write a single line or two summary here and then include an `overview` section with a more thorough synopsis.  See one of the other existing pages (except for quickstart and contributing) for an example.

2019-01-03 23:24 UTC, GodloveD commented on environment_and_metadata.rst
> +environment section.
Of course the build environment section will need a link when we have that page.  Might be good to go ahead and add it now so we don't forget.  afaik the link will not show up if it doesn't exist, but it will give us a build warning which will serve as a reminder.

2019-01-03 23:24 UTC, GodloveD commented on environment_and_metadata.rst
> +If you build a container from Singularity Hub or Docker Hub, the
Please change all instances of `Singularity Hub` to `Container Library` and link where appropriate.

2019-01-03 23:24 UTC, GodloveD commented on environment_and_metadata.rst
> +also define custom environment variables in your Recipe file as follows:
Please change all instances of the word `Recipe` to `definition file`.

2019-01-03 23:24 UTC, GodloveD commented on environment_and_metadata.rst
> +
remove extraneous newlines

2019-01-03 23:24 UTC, GodloveD commented on environment_and_metadata.rst
> +    Bootstrap: shub
Bootstrap all examples form the container library instead plz.

2019-01-03 23:24 UTC, GodloveD commented on environment_and_metadata.rst
> +Of course if nothing is redirected to ``$SINGULARITY_ENVIRONMENT`` in the ``%post`` section, the file ``/.singularity.d/env/91-environment.sh`` will be empty.
Actually it won't exist.

2019-01-03 23:24 UTC, GodloveD commented on environment_and_metadata.rst
> +
plz remove all of these spaces!

2019-01-03 23:24 UTC, GodloveD commented on environment_and_metadata.rst
> +Notice the ``--cleanenv`` in the example above? That argument specifies that we want
It's a bit cute to try to nest the `--cleanenv` example within another example, but it's not the best idea imho.  It should be easy to locate things quickly in the technical docs and people who are specifically looking for the `--cleanenv` option might have a tough time finding it buried like this.  Better to break it out into a seperate example.

2019-01-03 23:24 UTC, GodloveD commented on environment_and_metadata.rst
> +The ``inspect`` command is useful for viewing labels and other container meta-data.
Maybe `inspect` needs its own section.  It has lots o options.

2019-01-03 23:24 UTC, GodloveD commented on environment_and_metadata.rst
> +
omg these newlines!!!  🤢

2019-01-03 23:24 UTC, GodloveD commented on environment_and_metadata.rst
> +   container to carry out the action commands. (e.g. ``exec`` , ``run`` or ``shell``)
In later versions of Singularity these files may be dynamically written at runtime.

2019-01-07 12:53 UTC, devprincess commented on environment_and_metadata.rst
> +
oh these spaces are needed in the code blocks, otherwise when showing up in html format for the sphinx template, the space in between is too small between lines that some words might overlap @GodloveD

2019-01-07 12:58 UTC, devprincess commented on environment_and_metadata.rst
> +
yup again, the sphinx theme spacing does not look good on code blocks, I could remove these lines, but words between lines could overlap @GodloveD

2019-01-07 12:59 UTC, devprincess commented on appendix.rst
> +#. **SINGULARITY_ENVIRONMENT**: Contains all the environment variables that have been exported in your container.
Awesome, I'll add these changes on a separate PR :+1: @GodloveD

2019-01-07 17:14 UTC, WestleyK commented on environment_and_metadata.rst
> +    .. code-block:: none
I think you can use `.. code-block:: singularity` instead of `.. code-block:: none`.

2019-01-07 17:16 UTC, WestleyK commented on environment_and_metadata.rst
> +      singularity inspect mysifimage.sif
Probably add a `$` before the command.

2019-01-07 17:23 UTC, WestleyK commented on environment_and_metadata.rst
> +      Like this:
I think the next 4 lines have extra white space,
```
      Of course, all of these labels will be shown by default, so to add new custom labels you
      should use the ``%labels`` section in your definition file.
      [...]
```
 To:

```
Of course, all of these labels will be shown by default, so to add new custom labels you
should use the ``%labels`` section in your definition file.
[...]
```

2019-01-07 19:10 UTC, devprincess commented on environment_and_metadata.rst
> +The ``inspect`` command is useful for viewing labels and other container meta-data.
added! thanks @GodloveD

2019-01-07 19:14 UTC, devprincess commented
@WestleyK @GodloveD nevermind on the blank lines on code blocks, changing all code block sections to `code-block: singularity` it works perfectly, adding that on the next commit :+1:

2019-01-08 22:39 UTC, GodloveD approved these changes

2019-01-08 22:40 UTC, GodloveD commented
I added a commit to this myself, and I think it looks fine now.  Can someone else (@devprincess if you like) give it one more look and either merge or make suggest any new changes?

2019-01-09 05:57 UTC, devprincess commented
@GodloveD looks good in my opinion, just added a small change to uppercase `Bootstrap` and `From` on a def file example, think this can move forward, thanks !

2019-01-09 05:57 UTC, merged