add Pygments lexer for Singularity definition files
apptainer/singularity-userdocs pull request #54
Opened 2018-12-30 06:25 UTC by hall

## Description of the Pull Request (PR):

These changes add a local Pygments lexer for Singularity definition files; e.g.:

![deepinscreenshot_select-area_20181230010709](https://user-images.githubusercontent.com/32495955/50544804-509b4680-0bcf-11e9-8d3a-4da1b1f59127.png)

Here's a test file (an image since GitHub doesn't allow HTML):

![deepinscreenshot_select-area_20181230010603](https://user-images.githubusercontent.com/32495955/50544799-1fbb1180-0bcf-11e9-8d15-6f0df0d3d79f.png)

I'll also be adding this into the upstream repo so feel free to close this PR if you'd rather wait for that. I'm not incredibly familiar with the definition file syntax so I'm mostly looking for feedback before attempting to add the lexer into Pygments.

## This fixes or addresses the following GitHub issues:

- None

2018-12-30 06:45 UTC, jmstover approved these changes
This looks good to me.

@devprincess ?? You have much more experience here with Sphinx, etc.. than I.

2019-01-03 19:16 UTC, GodloveD requested changes
@hall thanks very much for this contribution!  I think it will really help make the docs more readable, and the syntax highlighting is a useful addition to the pygments package as well.

Just a few suggestions for improvement here. 

I'm happy to include this as is.  Maybe you can submit another PR when this is merged upstream?  

Thanks again!

2019-01-03 19:16 UTC, GodloveD commented on pygments_singularity.py
> +    _section = r'^%(?:post|setup|environment|help|labels|test|runscript|files|startscript)\b'
Add `pre` to `_section` (undocumented as of now).

2019-01-03 19:16 UTC, GodloveD commented on pygments_singularity.py
> +    _headers = r'^(\s)*(bootstrap|from|osversion|mirrorurl|include)(:)'
Some other `_headers` should be added.  For instance, `Registry`, `Namespace`, `IncludeCMD`.  See the `Keywords` sections in the appendix for info.

2019-01-03 23:32 UTC, hall commented
Thanks for the feedback, @GodloveD! I'll make a note to remove these changes after they're merged upstream.

2019-01-03 23:47 UTC, hall commented
Here's the upstream PR:

https://bitbucket.org/birkenfeld/pygments-main/pull-requests/793/add-singularity-lexer/diff

2019-01-04 03:18 UTC, GodloveD approved these changes

2019-01-04 03:21 UTC, GodloveD commented
Thanks again @hall !

2019-01-04 03:21 UTC, merged