Running Services Page Added
apptainer/singularity-userdocs pull request #57
Opened 2019-01-04 21:48 UTC by sushma-98

## Description of the Pull Request (PR):

Write your description of the PR here. Be sure to include as much background,
and details necessary for the reviewers to understand exactly what this is
fixing or enhancing.

## This fixes or addresses the following GitHub issues:

- Fixes #

2019-01-04 22:19 UTC, jmstover commented on running_services.rst
> +``singularity pull``.
Is this in the library somewhere already? If so what's the `library://` location for the `pull`?

2019-01-06 14:31 UTC, sushma-98 commented on running_services.rst
> +``singularity pull``.
I wanted to upload it to the container library and then write a pull command for it, but the image file was very heavy so couldn't upload. @GodloveD suggested we should use rather a simple example. We should first decide if we want to demonstrate this url-pdf example at all, or do we have a better and easier example.

2019-01-06 15:29 UTC, jmstover commented on running_services.rst
> +``singularity pull``.
My biggest complaint as written, is you're saying:  "To download image from the library run [...]" ... but not giving a library location for the image. How big is the image when built?

@GodloveD  We should put the url-to-pdf definition file up on the examples repository. The full definition file can be linked to within the text, as well as the description of it that's there.

2019-01-08 16:12 UTC, sushma-98 commented on running_services.rst
> +``singularity pull``.
The image size is 0.5 GB. So it was taking forever to push it to the container library. That is why the pull command in doc is incomplete.

2019-01-08 17:31 UTC, jmstover commented on running_services.rst
> +``singularity pull``.
Right... but it's incomplete. I can get a unsigned copy up somewhere w/o an issue. Would that be enough?

@GodloveD

2019-01-08 21:22 UTC, GodloveD requested changes
Overall, I like the flow of the page and I think the pdf example works fine.  500MB should not be too big for most folks to work with.  I have a ton of small suggestions and nitpicks.

2019-01-08 21:22 UTC, GodloveD commented on running_services.rst
> +
Please have a 1 or 2 sentence explanation of what a service is, then an overview section and a slightly more in depth explanation.  See the other pages for examples.

2019-01-08 21:22 UTC, GodloveD commented on running_services.rst
> +Until now, you have run Singularity containers in the foreground. But what if you want to run services
The phrasing of this (`Until now,`) sort of assumes that the user is going through the manual step-by-step as though it's a tutorial.  That's unlikely to be the case.

2019-01-08 21:22 UTC, GodloveD commented on running_services.rst
> +    apt-get update && apt-get install -y nginx
For consistency, all commands should start with a `$`.

2019-01-08 21:22 UTC, GodloveD commented on running_services.rst
> +Suppose you want to run a web server, with nginx,
This is a run-on sentence (3 sentences joined by commas).

2019-01-08 21:22 UTC, GodloveD commented on running_services.rst
> +previously built.
Once again, it was only "`previously built`" if the user is going through the technical manual step by step, which is unlikely to be the case imho.

2019-01-08 21:22 UTC, GodloveD commented on running_services.rst
> +    If you ``start`` an instance with sudo and then ``run`` it without sudo, it
I think change `run` to `list` at this point.

2019-01-08 21:22 UTC, GodloveD commented on running_services.rst
> +
redundant spaces like this should be removed throughout all code blocks.

2019-01-08 21:22 UTC, GodloveD commented on running_services.rst
> +    Singularity lolcow_latest.sif:~> exec cowsay Instance
remove the `exec` command for clarity here.

2019-01-08 21:22 UTC, GodloveD commented on running_services.rst
> +Now, since you are familiar with instances, the following illustrates a more
I think we should strive for a less conversational tone throughout this page.

2019-01-08 21:22 UTC, GodloveD commented on running_services.rst
> +
remove redundant spaces again.

2019-01-08 21:22 UTC, GodloveD commented on running_services.rst
> +All this does is, download the official nginx Docker container, convert
The `%startscript` is a new concept that has not yet been introduced at this point.  May be good to spend a little more time talking about it.

2019-01-08 21:22 UTC, GodloveD commented on running_services.rst
> +    $ singularity build nginx.sif nginx.def
Both of these commands must be run as root.

2019-01-08 21:22 UTC, GodloveD commented on running_services.rst
> +            $ sudo singularity instance start --writable-tmpfs ng.sif web
I think the command should just be written like this and then a note should be included to explain why the `sudo` and `--writable-tmpfs` are necessary.

2019-01-08 21:22 UTC, GodloveD commented on running_services.rst
> +Just like that we’ve downloaded, built, and ran an nginx Singularity
"ran" to "run" (as in "have run")

2019-01-08 21:22 UTC, GodloveD commented on running_services.rst
> +``singularity pull``.
@jmstover yes.  Please do so.  And if you or @sushma-98 can also add this example to the `examples` repo that would be very good as well.  500MB is not too big for us to use imho.

2019-01-08 21:22 UTC, GodloveD commented on running_services.rst
> +.. code-block:: none
Update to the latest version of master and change `none` to `singularity` so we get some syntax highlighting goodness.

2019-01-08 21:22 UTC, GodloveD commented on running_services.rst
> +singularity. If you haven’t already, check out the :ref:`Singularity app documentation <reproducible-scif-apps>`
I don't think we are going to be updating that page so link to the SCIF manifesto instead.  https://sci-f.github.io/

2019-01-08 21:22 UTC, GodloveD commented on running_services.rst
> +    $ singularity instance.start -B out/:/scif/data/pdf_client/output/ url-to-pdf-api.img pdf
the dot syntax is not supported in 3.0.  Be sure to test all commands.

2019-01-08 21:22 UTC, GodloveD commented on running_services.rst
> +    google.pdf
Might be nice to show a screenshot of the pdf that is created.  Also would be better to use sylabs.io as the example website instead of google imho.

2019-01-10 20:19 UTC, sushma-98 commented on running_services.rst
> +previously built.
Linked it to the quickstart page where we first built the lolcow.

2019-01-11 01:09 UTC, sushma-98 commented on running_services.rst
> +
Do you mean the space between columns? This is how if appears on my terminal. Just copy-pasted it
![screenshot from 2019-01-11 01-56-27](https://user-images.githubusercontent.com/45898293/51006932-792a2580-156b-11e9-8c3e-dc52ad266a01.png)

2019-01-11 02:04 UTC, sushma-98 commented on running_services.rst
> +
I think you mean the blank lines between two lines in code blocks. Fixed it!

2019-01-11 02:10 UTC, sushma-98 commented on running_services.rst
> +    $ singularity build nginx.sif nginx.def
Just to highlight the importance of SUDO, I've written these commands without sudo but mentioned to use sudo in a note right after these two lines. 
These start command will also need --writable-tmpfs, which also has been mentioned in the note. 

Do you prefer to keep the commands with sudo and tmpfs right here?

2019-01-11 02:41 UTC, sushma-98 commented on running_services.rst
> +    google.pdf
13 pages long pdf is being generated with sylabs website. Which screen shot should we use?
Also, the pages captured are inconsistent in terms of font sizes and picture alignments.

2019-01-11 02:46 UTC, sushma-98 commented on running_services.rst
> +``singularity pull``.
@jmstover Please send the link if you've manged to upload the image file somewhere.

2019-01-13 07:24 UTC, sushma-98 commented on running_services.rst
> +All this does is, download the official nginx Docker container, convert
Linked it to the definition files section

2019-01-14 12:56 UTC, jchavezlavalle requested changes
left some comments around here @sushma-98 thanks ! :+1:

2019-01-14 12:56 UTC, devprincess commented on running_services.rst
> +    If there occurs an error related to Port connection being refused while staring
no need to uppercase Port here .. also there's a typo in " being refused while **starting** the instance... "

2019-01-14 12:56 UTC, devprincess commented on running_services.rst
> +Now we want to define the pdf\_client app, which we will run to send the
syntax here from `pdf\_client` to ``pdf_client`` to be consistent with lines below

2019-01-14 12:56 UTC, devprincess commented on running_services.rst
> +When you are finished, use the instance.stop command to close all
commands like `instance.stop` and `instance.start` are deprecated, now the syntax has been changed to `instance start` and `instance stop` respectively

2019-01-14 12:56 UTC, devprincess commented on running_services.rst
> +        $ singularity instance start -B output/dir/outside/:/output/ nginx.sif  web
yes this is the way, make sure to use this same syntax for the instance stop command @sushma-98 :+1:

2019-01-18 10:20 UTC, jchavezlavalle requested changes

2019-01-18 10:20 UTC, devprincess commented on running_services.rst
> +    $ singularity build nginx.sif nginx.def
Are these 2 different containers? I ask because first it's built a `nginx.sif` (line 164) and then an instance from `ng.sif` is started on line 165 @sushma-98

2019-01-18 10:20 UTC, devprincess commented on running_services.rst
> +| Puppeteer also requires a few dependencies to be manually installed in
Remove this pipe here

2019-01-18 10:20 UTC, devprincess commented on running_services.rst
> +You should see a PDDF file file being generated like the one below:
typo on PDF here

2019-01-22 16:08 UTC, GodloveD approved these changes

2019-01-24 00:24 UTC, jchavezlavalle approved these changes
lgtm now, could you rebase this PR @sushma-98 ? lmk if you need help for this, thank you! :+1:

2019-01-25 16:46 UTC, jmstover commented on running_services.rst
> +    $ singularity instance stop \*
Wouldn't you want to only stop the `pdf` instance? 

And a FYI, you can do:
```
singularity instance stop -a
```
To stop all instances.

2019-01-26 02:05 UTC, GodloveD commented
Thanks @sushma-98 @devprincess and @jmstover !

2019-01-26 02:05 UTC, merged