Initial draft of Singularity and Docker interoperability
apptainer/singularity-userdocs pull request #58
Opened 2019-01-07 21:02 UTC by syl-ilumb

## Description of the Pull Request (PR):

Documentation updated for Singularity 3.0. Includes interaction with public and private images hosted via the Docker Hub using `pull` and `build`. Private images are accessed via authenticated means - interactive login or environment variables. 

## This fixes or addresses the following GitHub issues:

- Fixes #39

2019-01-14 13:04 UTC, jchavezlavalle requested changes
Added some comments around here @syl-ilumb thanks! :+1:

2019-01-14 13:04 UTC, jchavezlavalle commented on singularity_and_docker.rst
> +In our example ``docker://godlovedc/lolcow``, ``godlovedc`` specifies a Docker Hub user, whereas ``lolcow`` is the name of the repository. Adding the option to specifiy an image tag, the generic vers
typo here on .. "Adding the option to **specify** an image tag..."

2019-01-14 13:04 UTC, jchavezlavalle commented on singularity_and_docker.rst
> +After successful authentication, Singularity can also make use of pre-built *private* images available from the `Docker Hub <https://hub.docker.com/>`_. The three means available for authentication f
typo on "it is instructive to **illustrate** the error.."

2019-01-14 13:04 UTC, devprincess commented on singularity_and_docker.rst
> +will retrieve a specific version of the `PyTorch platform <https://pytorch.org/>`_ for Deep Learning from the NVIDIA GPU Cloud (NGC). Because NGC is a private registry, the above ``pull`` assumes :re
missing context here -> "This container we have just pulled".. will retrieve a specific version of .....

2019-01-28 22:00 UTC, syl-ilumb commented
Complete draft for review by @GodloveD & @devprincess please ...

2019-01-29 03:38 UTC, WestleyK commented on singularity_and_docker.rst
> +    sudo singularity build lolcow.sif lolcow.def
I would a `$` before the command:

```suggestion
    $ sudo singularity build lolcow.sif lolcow.def
```

2019-01-29 03:40 UTC, WestleyK commented on singularity_and_docker.rst
> +    sudo singularity build --docker-login mylolcow.sif mylolcow.def
Here to:

```suggestion
    $ sudo singularity build --docker-login mylolcow.sif mylolcow.def 
```

2019-01-29 03:41 UTC, WestleyK commented on singularity_and_docker.rst
> +    sudo -E singularity build mylolcow.sif mylolcow.def
```suggestion
    $ sudo -E singularity build mylolcow.sif mylolcow.def
```

2019-01-29 03:46 UTC, WestleyK commented on singularity_and_docker.rst
> +    #Custom environment shell code should follow
I would add a space here:

```suggestion
    # Custom environment shell code should follow
```

2019-01-29 15:04 UTC, syl-ilumb commented on singularity_and_docker.rst
> +    sudo singularity build lolcow.sif lolcow.def
Addressed - thx!

2019-01-29 15:35 UTC, syl-ilumb commented on singularity_and_docker.rst
> +    #Custom environment shell code should follow
This is output harvested _directly_ from Singularity ... I could apply your suggestion to improve the visual clarity, but it's not exactly what users will see ... What do you think?

2019-01-29 15:35 UTC, syl-ilumb commented on singularity_and_docker.rst
> +    sudo singularity build --docker-login mylolcow.sif mylolcow.def
Addressed - thx!

2019-01-29 16:33 UTC, WestleyK commented on singularity_and_docker.rst
> +    #Custom environment shell code should follow
Ohh, In that case I would still put a space there, then make a PR to Singularity to fix that. Although PING @GodloveD about this...

2019-01-29 16:40 UTC, WestleyK commented on singularity_and_docker.rst
> +.. code-block:: none
There is a extra space here:

```suggestion
.. code-block:: none
```

<br>

How did you miss this? :roll_eyes: lol!

2019-01-29 18:10 UTC, 0xaf1f commented on singularity_and_docker.rst
> +After describing various :ref:`action commands that could be applied to images hosted remotely via the Docker Hub <sec:action_co
I made this comment on slack, but perhaps it's better I do so here.

There are also some tips at https://github.com/singularityware/docker2singularity#tips-for-making-docker-images-compatible-with-singularity that I think would be best to harmonize/combine with this list.

2019-01-30 15:23 UTC, syl-ilumb commented on singularity_and_docker.rst
> +After describing various :ref:`action commands that could be applied to images hosted remotely via the Docker Hub <sec:action_co
Greatly appreciated @0xaf1f! I will proceed as you've suggested.

2019-01-31 16:54 UTC, syl-ilumb commented on singularity_and_docker.rst
> +.. code-block:: none
I beg your forgiveness ;-)

2019-01-31 21:11 UTC, ikaneshiro approved these changes
LGTM from a technical perspective. The section on oci and our cache is particularly cool :+1:

2019-01-31 21:16 UTC, 0xaf1f commented on singularity_and_docker.rst
> +Here ``docker`` is prepended to ensure that the ``run`` command of Singularity is instructed to boostrap container creation based upon this Docker image, thus creating a complete URI for Singularity.
I think it'd be good to note the cache location as being `$HOME/.singularity` by default and remind the reader that it's customizable via the `SINGULARITY_CACHEDIR` variable, with a link to the section in the docs that describes it in more detail.

2019-01-31 21:16 UTC, 0xaf1f commented on singularity_and_docker.rst
> +From this it is evident that use is being made of Ubuntu 16.04 *within* this container, whereas the shell *external* to the container is running a more-recent release of Ubuntu (not illustrated here)
delete hyphen in "more-recent release"

2019-01-31 21:16 UTC, 0xaf1f commented on singularity_and_docker.rst
> +    $ sudo docker images
`sudo` isn't required if the user is a member of the `docker` group. And if that's the case, can `singularity build ... docker-daemon:...` be run without `sudo` as well?

2019-01-31 21:16 UTC, 0xaf1f commented on singularity_and_docker.rst
> +Remotely Hosted and Built Containers
I think a clearer title would be something like "Remotely Building Containers". "Built" reads as pre-existing.

A related point-- I also think that "pre-existing" was extraneous in the earlier section headings  ("accessing pre-existing images from ...").

2019-01-31 21:16 UTC, 0xaf1f commented on singularity_and_docker.rst
> +Akin to a set of blueprints that explain how to build a custom container, Singularity definition files (or "def files") are considered in detail :ref:`elsewhere in this manual <definition-files>`. Th
Are `docker-daemon`, `docker-archive`, and the other new agents going to at least be listed on this page: https://www.sylabs.io/guides/3.0/user-guide/definition_files.html#header

2019-01-31 22:04 UTC, syl-ilumb commented on singularity_and_docker.rst
> +Here ``docker`` is prepended to ensure that the ``run`` command of Singularity is instructed to boostrap container creation based upon this Docker image, thus creating a complete URI for Singularity.
Agreed. Will address, @0xaf1f. Thanks!

2019-02-01 07:30 UTC, WestleyK commented on singularity_and_docker.rst
> +After describing various :ref:`action commands that could be applied to images hosted remotely via the Docker Hub <sec:action_co
It might be worth to add the `singularity cache clean` command here:

```suggestion
Cache maintenance is a manual process at the current time. In other words, the cache can be cleared by using the ``singularity cache clean`` command. By default, this will clean only blobs, use the ``--all`` flag to clean all cache.
```

Or something like that... Maybe...

2019-02-08 14:34 UTC, syl-ilumb commented on singularity_and_docker.rst
> +Akin to a set of blueprints that explain how to build a custom container, Singularity definition files (or "def files") are considered in detail :ref:`elsewhere in this manual <definition-files>`. Th
Created issue https://github.com/sylabs/singularity-userdocs/issues/93 - thx!

2019-02-08 14:39 UTC, syl-ilumb commented on singularity_and_docker.rst
> +After describing various :ref:`action commands that could be applied to images hosted remotely via the Docker Hub <sec:action_co
Absolutely. We'll defer that to a subsequent PR. Note https://github.com/sylabs/singularity-userdocs/issues/94. Thx!

2019-02-08 14:41 UTC, syl-ilumb commented on singularity_and_docker.rst
> +    #Custom environment shell code should follow
@GodloveD: Looks like we need to file a separate issue here that is not docs oriented in nature. Agreed?

2019-02-08 14:46 UTC, syl-ilumb commented on singularity_and_docker.rst
> +.. code-block:: none
This'll be fixed in my next update - thx

2019-02-08 15:26 UTC, syl-ilumb commented on singularity_and_docker.rst
> +Here ``docker`` is prepended to ensure that the ``run`` command of Singularity is instructed to boostrap container creation based upon this Docker image, thus creating a complete URI for Singularity.
Added a note at the outset _and_ a best practice at the end - thanks, @0xaf1f !!!

2019-02-08 15:56 UTC, jchavezlavalle approved these changes

2019-02-08 16:19 UTC, syl-ilumb commented on singularity_and_docker.rst
> +    #Custom environment shell code should follow
@WestleyK to raise elsewhere as an issue to be addressed ...

2019-02-08 16:28 UTC, devprincess commented on singularity_and_docker.rst
> +    #Custom environment shell code should follow
@syl-ilumb @WestleyK  I think this output is supposed to be something like: 

```
$ singularity inspect --environment lolcow_latest.sif 

==90-environment.sh==
#!/bin/sh
#Custom environment shell code should follow

```
where the filename is detailed at the very beginning?

2019-02-08 16:50 UTC, syl-ilumb commented on singularity_and_docker.rst
> +    #Custom environment shell code should follow
Updated output - thx @devprincess

2019-02-08 16:51 UTC, syl-ilumb commented on singularity_and_docker.rst
> +From this it is evident that use is being made of Ubuntu 16.04 *within* this container, whereas the shell *external* to the container is running a more-recent release of Ubuntu (not illustrated here)
Removed

2019-02-08 18:19 UTC, syl-ilumb commented on singularity_and_docker.rst
> +Remotely Hosted and Built Containers
Agreed - on both counts. Section revised accordingly. Thx @0xaf1f.

2019-02-08 18:44 UTC, syl-ilumb commented on singularity_and_docker.rst
> +    $ sudo docker images
It can! Docs updated. Thx @0xaf1f!

2019-02-08 18:46 UTC, WestleyK commented on singularity_and_docker.rst
> +After describing various :ref:`action commands that could be applied to images hosted remotely via the Docker Hub <sec:action_co
Oh yeah, sorry I forgot this was for 3.0, not 3.1.

2019-02-09 15:42 UTC, syl-ilumb commented on singularity_and_docker.rst
> +After describing various :ref:`action commands that could be applied to images hosted remotely via the Docker Hub <sec:action_co
Harmonized/combined as suggested.

2019-02-19 05:52 UTC, GodloveD requested changes
Wow!  This was a hell of a lot of work!  Thanks @syl-ilumb!  

I'm suggesting some changes.  Mostly nitpicks.  But overall this looks very good.  After these are addressed I'm happy to merge.

2019-02-19 05:52 UTC, GodloveD commented on singularity_and_docker.rst
> +Here ``docker`` is prepended to ensure that the ``run`` command of Singularity is instructed to boostrap container creation based upon this Docker image, thus creating a complete URI for Singularity.
I'm confused.  My lolcow copy is cached at `$HOME/.singularity/cache/oci-tmp/a692b57abc43035b197b10390ea2c12855d21649f2ea2cc28094d18b93360eeb/lolcow_latest.sif`.  Is `org.opencontainers.image.ref.name` meant to denote the hash?  If so, please wrap it in gt and lt signs like so:
```
$HOME/.singularity/cache/oci-tmp/<org.opencontainers.image.ref.name>/lolcow_latest.sif
```
And then note that `<org.opencontainers.image.ref.name>` will be replaced by the appropriate hash for the container.

2019-02-19 05:52 UTC, GodloveD commented on singularity_and_docker.rst
> +As the runtime of this container is encapsulated as a single SIF file, it is possible to ``cd /home/vagrant/.singularity/cache/oci-tmp/a692b57abc43035b197b10390ea2c12855d21649f2ea2cc28094d18b93360eeb
wrap the `cd` command in a code block so that a scrollbar appears at the bottom.  On my screen this line continues to the right of the rest of the text.

2019-02-19 05:52 UTC, GodloveD commented on singularity_and_docker.rst
> +In our example ``docker://godlovedc/lolcow``, ``godlovedc`` specifies a Docker Hub user, whereas ``lolcow`` is the name of the repository. Adding the option to specifiy an image tag, the generic vers
I think that `<hub-user>` should just be `<user>` since this example assumes a registry other than Singularity hub.

2019-02-19 05:52 UTC, GodloveD commented on singularity_and_docker.rst
> +    export SINGULARITY_DOCKER_USERNAME=$oauthtoken
There's an error here I think.  Observe:
```
vagrant@vagrant:~$ export SINGULARITY_DOCKER_USERNAME=$oauthtoken
vagrant@vagrant:~$ echo $SINGULARITY_DOCKER_USERNAME

vagrant@vagrant:~$ export SINGULARITY_DOCKER_USERNAME='$oauthtoken'
vagrant@vagrant:~$ echo $SINGULARITY_DOCKER_USERNAME
$oauthtoken
```
Also might be useful to point out the that string `$oauthtoken` is meant to be taken literally and is not an env var.  This tripped me up when I first used NGC.

2019-02-19 05:52 UTC, GodloveD commented on singularity_and_docker.rst
> +    Enter Docker Username: $oauthtoken
plz double check that this works without quotes in light of comment above.

2019-02-19 05:52 UTC, GodloveD commented on singularity_and_docker.rst
> +    $ singularity build mylolcow_latest.sif docker://godlovedc/lolcow
change `mylolcow_latest_sandbox.sif` to `mylolcow_latest_sandbox` since a sandbox is not a sif.  (of course, make this change throughout the example.)

2019-02-19 05:52 UTC, GodloveD commented on singularity_and_docker.rst
> +Once you have an account for Sylabs Cloud, and have logged in to the portal, select `Remote Builder <https://cloud.sylabs.io/builder>`_. The right-hand side of this page is devoted to use of the Sing
Remove the `30-day` adjective.  It might be changed in the (near) future.

2019-02-19 05:52 UTC, GodloveD commented on singularity_and_docker.rst
> +
point out that no `sudo` was needed above just in case the reader misses the main reason for the `--remote` option.

2019-02-19 05:52 UTC, GodloveD commented on singularity_and_docker.rst
> +    $ tar tvf lolcow.tar
Is there a simple way to create a tarball such as this so that the reader can actually run this example?  I dug around for a while but couldn't figure it out.

2019-02-19 05:52 UTC, GodloveD commented on singularity_and_docker.rst
> +The ``Dockerfile`` corresponding to ``godlovedc/lolcow`` (and `available here <https://hub.docker.com/r/godlovedc/lolcow/dockerfile>`_) is as follows:
Good God, I guess I can never update this def file again after we publish this.  😜

2019-02-19 05:52 UTC, GodloveD commented on singularity_and_docker.rst
> +Suppose now that a Singularity `%runscript` **section** is added to the definition file as follows:
%runscript should have double backticks instead of single backticks around it.

2019-02-19 05:52 UTC, GodloveD commented on singularity_and_docker.rst
> +    1. If present, the %runscript section of the Singularity definition file is executed
Wrap %runscript in double backticks to indicate code.

2019-02-19 05:52 UTC, GodloveD commented on singularity_and_docker.rst
> +Container Metadata
I'm actually not sure how much this section adds.  I think you could just reference the section of the metadata page that [covers the inspect command](https://www.sylabs.io/guides/3.0/user-guide/environment_and_metadata.html#the-inspect-command) instead.  If you want to give an example of what a `runscript` would look like if it came directly from docker that is instructive.  But I think you can do so without this whole entire section.

2019-02-19 05:52 UTC, GodloveD commented on singularity_and_docker.rst
> +In this case, the ``lolcow`` image was hosted remotely via user ``godlovedc`` at the Docker Hub. On the other hand, the existence of ``docker-daemon`` in the output from ``inspect`` indicates that an
I think its a little weird that you refer to Docker Hub as _the_ Docker Hub throughout.  Just Docker Hub seems sufficient.

2019-02-19 05:52 UTC, GodloveD commented on singularity_and_docker.rst
> +    $ singularity inspect --env
There's a lot of different ideas bouncing around in this paragraph.  I think maybe the explanation about OCI needs to be moved into the overview, then maybe this paragraph can focus on how images from docker hub are stored as OCI blobs.

2019-02-19 05:52 UTC, GodloveD commented on singularity_and_docker.rst
> +    $ singularity inspect --env
I think this should actually be `cat blobs/sha256/73d5b1025fbfa138f2cacf45bbf3f61f7de891559fa25b28ab365c7d9c3cbd82 | jq`

2019-02-19 05:52 UTC, GodloveD commented on singularity_and_docker.rst
> +    $ singularity inspect --env
So, a casual user might be confused at this point as to why you are going to all the trouble to explain an alternate way for a user to build a container using a cache from a container they already built.  It is probably worthwhile to point out that this is a contrived example and and it will work with OCI bundles that are obtained elsewhere.  

I think it should also be made clear earlier in this section that the pull command produces an OCI bundle.

2019-02-19 05:52 UTC, GodloveD commented on singularity_and_docker.rst
> +    $ singularity inspect --env
I'm actually getting an error when I try this example:
```
vagrant@vagrant:~$ singularity build lolcow_oci_tarfile.sif oci-archive://godlovedc_lolcow.tar
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: error extracting the OCI archive file: open /tmp/temp-oci-035849548/mylolcow_latest_sandbox.sif/usr/share/man/pt/man8/apt-cache.8.gz: too many open files
```
Should I file an issue?

2019-02-19 05:52 UTC, GodloveD commented on singularity_and_docker.rst
> +    $ singularity inspect --env
Not in this branch.  😄

2019-02-19 05:52 UTC, GodloveD commented on singularity_and_docker.rst
> +    $ singularity inspect --env
There is only a single header in a def file. I think you are talking about the keywords that comprise that header.   Please update throughout.

2019-02-19 15:43 UTC, syl-ilumb commented on singularity_and_docker.rst
> +As the runtime of this container is encapsulated as a single SIF file, it is possible to ``cd /home/vagrant/.singularity/cache/oci-tmp/a692b57abc43035b197b10390ea2c12855d21649f2ea2cc28094d18b93360eeb
Done - thx

2019-02-19 15:46 UTC, syl-ilumb commented on singularity_and_docker.rst
> +In our example ``docker://godlovedc/lolcow``, ``godlovedc`` specifies a Docker Hub user, whereas ``lolcow`` is the name of the repository. Adding the option to specifiy an image tag, the generic vers
I was making use of [the Docker convention](https://docs.docker.com/docker-hub/repos/), @GodloveD. Please scroll down on this page to see what I am referring to. If you still feel strongly about this, I will concede and make the change.

2019-02-20 16:40 UTC, syl-ilumb commented on singularity_and_docker.rst
> +Here ``docker`` is prepended to ensure that the ``run`` command of Singularity is instructed to boostrap container creation based upon this Docker image, thus creating a complete URI for Singularity.
Much clearer - thanks for this!

2019-02-20 16:54 UTC, syl-ilumb commented on singularity_and_docker.rst
> +    export SINGULARITY_DOCKER_USERNAME=$oauthtoken
Both work for me:

```
vagrant@ubuntu-bionic:~$ export SINGULARITY_DOCKER_USERNAME=$oauthtoken
vagrant@ubuntu-bionic:~$ echo $SINGULARITY_DOCKER_USERNAME

vagrant@ubuntu-bionic:~$ export SINGULARITY_DOCKER_PASSWORD=NjVudDZ2YXJmanBiNzc3cWZnZTA5a25udHE6ZjUzNjAwMjEtZDc5YS00Njk4LWFlMTItNjRjMWVlMDNjZjky
vagrant@ubuntu-bionic:~$ singularity pull docker://nvcr.io/nvidia/pytorch:18.11-py3
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:18d680d616571900d78ee1c8fff0310f2a2afe39c6ed0ba2651ff667af406c3e
 41.34 MiB / 41.34 MiB [====================================================] 2s
Copying blob sha256:0addb6fece630456e0ab187b0aa4304d0851ba60576e7f6f9042a97ee908a796
 851 B / 851 B [============================================================] 0s
Copying blob sha256:78e58219b215b359fe002f0ca1f416617b75ca9b36cb274c98d7a5f808711179
 620 B / 620 B [============================================================] 0s
Copying blob sha256:eb6959a66df2ea26a26452ba11f84fb64bb45af90204374862ec71ee59f795e7
 169 B / 169 B [============================================================] 0s
Copying blob sha256:4628c5124b80950f1e80165669d5e788292a8240b4c14a62cfa477db8e454191
 4.73 MiB / 9.71 MiB [===========================>-----------------------------]^Cvagrant@ubuntu-bionic:~$ 
```

_and_

```
vagrant@ubuntu-bionic:~$ export SINGULARITY_DOCKER_USERNAME='$oauthtoken'
vagrant@ubuntu-bionic:~$ echo $SINGULARITY_DOCKER_USERNAME
$oauthtoken
vagrant@ubuntu-bionic:~$ singularity pull docker://nvcr.io/nvidia/pytorch:18.11-py3
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:18d680d616571900d78ee1c8fff0310f2a2afe39c6ed0ba2651ff667af406c3e
Skipping fetch of repeat blob sha256:0addb6fece630456e0ab187b0aa4304d0851ba60576e7f6f9042a97ee908a796
Skipping fetch of repeat blob sha256:78e58219b215b359fe002f0ca1f416617b75ca9b36cb274c98d7a5f808711179
Skipping fetch of repeat blob sha256:eb6959a66df2ea26a26452ba11f84fb64bb45af90204374862ec71ee59f795e7
Skipping fetch of repeat blob sha256:4628c5124b80950f1e80165669d5e788292a8240b4c14a62cfa477db8e454191
Copying blob sha256:48caf7a8cf74b4fc8c8e44567683755d68c15e5fecc0eae1a4d9a4690b835d2d
 12.72 KiB / 12.72 KiB [====================================================] 0s
Copying blob sha256:c0d9cf2ad624d152c6933ea7a05dafa26f0ba9125c91c25a47387b914310e590
 4.95 KiB / 4.95 KiB [======================================================] 0s
Copying blob sha256:47e67a425dc353e975235badad98d60f6dc913b9c59acd9879f00c8aa75ca18c
^Cvagrant@ubuntu-bionic:~$ 
```

Perhaps the use of single quotes is more useful?

2019-02-20 17:04 UTC, syl-ilumb commented on singularity_and_docker.rst
> +    export SINGULARITY_DOCKER_USERNAME=$oauthtoken
Updated to make use of single quotes, as this results in more useful output when the env varb is echo'd.

Added note re: taking `$oauthtoken` literally.

2019-02-20 17:11 UTC, syl-ilumb commented on singularity_and_docker.rst
> +    Enter Docker Username: $oauthtoken
It does. in fact:

```
vagrant@ubuntu-bionic:~$ singularity pull --docker-login docker://nvcr.io/nvidia/pytorch:18.11-py3
Enter Docker Username: $oauthtoken
Enter Docker Password: 
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:18d680d616571900d78ee1c8fff0310f2a2afe39c6ed0ba2651ff667af406c3e
 9.56 MiB / 41.34 MiB [============>-------------------------------------------]^Cvagrant@ubuntu-bionic:~$ 
vagrant@ubuntu-bionic:~$ singularity pull --docker-login docker://nvcr.io/nvidia/pytorch:18.11-py3
Enter Docker Username: '$oauthtoken'
Enter Docker Password: 
INFO:    Starting build...
FATAL:   Unable to pull docker://nvcr.io/nvidia/pytorch:18.11-py3: conveyor failed to get: unable to retrieve auth token: invalid username/password
```

2019-02-20 17:30 UTC, syl-ilumb commented on singularity_and_docker.rst
> +In this case, the ``lolcow`` image was hosted remotely via user ``godlovedc`` at the Docker Hub. On the other hand, the existence of ``docker-daemon`` in the output from ``inspect`` indicates that an
Global find-and-replace executed ...

2019-02-20 17:32 UTC, syl-ilumb commented on singularity_and_docker.rst
> +    1. If present, the %runscript section of the Singularity definition file is executed
Nice catch - thx!

2019-02-20 17:33 UTC, syl-ilumb commented on singularity_and_docker.rst
> +Suppose now that a Singularity `%runscript` **section** is added to the definition file as follows:
Indeed - thx!

2019-02-20 17:36 UTC, syl-ilumb commented on singularity_and_docker.rst
> +    $ singularity build mylolcow_latest.sif docker://godlovedc/lolcow
Applied - nice catch! Thx!

2019-02-20 17:37 UTC, syl-ilumb commented on singularity_and_docker.rst
> +Once you have an account for Sylabs Cloud, and have logged in to the portal, select `Remote Builder <https://cloud.sylabs.io/builder>`_. The right-hand side of this page is devoted to use of the Sing
Done!

2019-02-20 17:38 UTC, syl-ilumb commented on singularity_and_docker.rst
> +The ``Dockerfile`` corresponding to ``godlovedc/lolcow`` (and `available here <https://hub.docker.com/r/godlovedc/lolcow/dockerfile>`_) is as follows:
Correct! You would require my consent, along with an update of this document.

2019-02-20 17:52 UTC, syl-ilumb commented on singularity_and_docker.rst
> +
Note added.

2019-02-20 18:30 UTC, syl-ilumb commented on singularity_and_docker.rst
> +    $ tar tvf lolcow.tar
Added instructions - it's all about `sudo docker save 577c1fe8e6d8 -o lolcow.tar`, where `577c1fe8e6d8` is the ID of an image cached locally by Docker. So, you do need Docker installed for this.

2019-02-20 18:43 UTC, syl-ilumb commented on singularity_and_docker.rst
> +    $ singularity inspect --env
Agreed - thx for catching that!

2019-02-20 18:52 UTC, syl-ilumb commented on singularity_and_docker.rst
> +    $ singularity inspect --env
Did you try the example documented involving `alpine`? Just confirmed it works ...

2019-02-20 19:08 UTC, syl-ilumb commented on singularity_and_docker.rst
> +    $ singularity inspect --env
What does `tar tvf godlovedc_lolcow.tar` reveal?

I can do:

```
$ singularity pull docker://godlovedc/lolcow
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:9fb6c798fa41e509b58bccc5c29654c3ff4648b608f5daa67c1aab6a7d02c118
 45.33 MiB / 45.33 MiB [====================================================] 2s
Copying blob sha256:3b61febd4aefe982e0cb9c696d415137384d1a01052b50a85aae46439e15e49a
 848 B / 848 B [============================================================] 0s
Copying blob sha256:9d99b9777eb02b8943c0e72d7a7baec5c782f8fd976825c9d3fb48b3101aacc2
 621 B / 621 B [============================================================] 0s
Copying blob sha256:d010c8cf75d7eb5d2504d5ffa0d19696e8d745a457dd8d28ec6dd41d3763617e
 853 B / 853 B [============================================================] 0s
Copying blob sha256:7fac07fb303e0589b9c23e6f49d5dc1ff9d6f3c8c88cabe768b430bdb47f03a9
 169 B / 169 B [============================================================] 0s
Copying blob sha256:8e860504ff1ee5dc7953672d128ce1e4aa4d8e3716eb39fe710b849c64b20945
 53.75 MiB / 53.75 MiB [====================================================] 2s
Copying config sha256:73d5b1025fbfa138f2cacf45bbf3f61f7de891559fa25b28ab365c7d9c3cbd82
 3.33 KiB / 3.33 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: lolcow_latest.sif

vagrant@ubuntu-bionic:~/.singularity/cache/oci$ tree
.
├── blobs
│   └── sha256
│       ├── 3b61febd4aefe982e0cb9c696d415137384d1a01052b50a85aae46439e15e49a
│       ├── 73d5b1025fbfa138f2cacf45bbf3f61f7de891559fa25b28ab365c7d9c3cbd82
│       ├── 7fac07fb303e0589b9c23e6f49d5dc1ff9d6f3c8c88cabe768b430bdb47f03a9
│       ├── 8e860504ff1ee5dc7953672d128ce1e4aa4d8e3716eb39fe710b849c64b20945
│       ├── 9d99b9777eb02b8943c0e72d7a7baec5c782f8fd976825c9d3fb48b3101aacc2
│       ├── 9fb6c798fa41e509b58bccc5c29654c3ff4648b608f5daa67c1aab6a7d02c118
│       ├── d010c8cf75d7eb5d2504d5ffa0d19696e8d745a457dd8d28ec6dd41d3763617e
│       └── f2a852991b0a36a9f3d6b2a33b98a461e9ede8393482f0deb5287afcbae2ce10
├── index.json
└── oci-layout

2 directories, 10 files
vagrant@ubuntu-bionic:~/.singularity/cache/oci$ tar cvf ~/lolcow.tar *
blobs/
blobs/sha256/
blobs/sha256/73d5b1025fbfa138f2cacf45bbf3f61f7de891559fa25b28ab365c7d9c3cbd82
blobs/sha256/f2a852991b0a36a9f3d6b2a33b98a461e9ede8393482f0deb5287afcbae2ce10
blobs/sha256/7fac07fb303e0589b9c23e6f49d5dc1ff9d6f3c8c88cabe768b430bdb47f03a9
blobs/sha256/9fb6c798fa41e509b58bccc5c29654c3ff4648b608f5daa67c1aab6a7d02c118
blobs/sha256/3b61febd4aefe982e0cb9c696d415137384d1a01052b50a85aae46439e15e49a
blobs/sha256/d010c8cf75d7eb5d2504d5ffa0d19696e8d745a457dd8d28ec6dd41d3763617e
blobs/sha256/9d99b9777eb02b8943c0e72d7a7baec5c782f8fd976825c9d3fb48b3101aacc2
blobs/sha256/8e860504ff1ee5dc7953672d128ce1e4aa4d8e3716eb39fe710b849c64b20945
index.json
oci-layout

vagrant@ubuntu-bionic:~$ tar tvf lolcow.tar 
drwxr-xr-x vagrant/vagrant   0 2019-02-20 18:53 blobs/
drwxr-xr-x vagrant/vagrant   0 2019-02-20 18:53 blobs/sha256/
-rw-r--r-- vagrant/vagrant 3410 2019-02-20 18:53 blobs/sha256/73d5b1025fbfa138f2cacf45bbf3f61f7de891559fa25b28ab365c7d9c3cbd82
-rw-r--r-- vagrant/vagrant 1125 2019-02-20 18:53 blobs/sha256/f2a852991b0a36a9f3d6b2a33b98a461e9ede8393482f0deb5287afcbae2ce10
-rw-r--r-- vagrant/vagrant  169 2019-02-20 18:53 blobs/sha256/7fac07fb303e0589b9c23e6f49d5dc1ff9d6f3c8c88cabe768b430bdb47f03a9
-rw-r--r-- vagrant/vagrant 47536248 2019-02-20 18:53 blobs/sha256/9fb6c798fa41e509b58bccc5c29654c3ff4648b608f5daa67c1aab6a7d02c118
-rw-r--r-- vagrant/vagrant      848 2019-02-20 18:53 blobs/sha256/3b61febd4aefe982e0cb9c696d415137384d1a01052b50a85aae46439e15e49a
-rw-r--r-- vagrant/vagrant      853 2019-02-20 18:53 blobs/sha256/d010c8cf75d7eb5d2504d5ffa0d19696e8d745a457dd8d28ec6dd41d3763617e
-rw-r--r-- vagrant/vagrant      621 2019-02-20 18:53 blobs/sha256/9d99b9777eb02b8943c0e72d7a7baec5c782f8fd976825c9d3fb48b3101aacc2
-rw-r--r-- vagrant/vagrant 56355961 2019-02-20 18:53 blobs/sha256/8e860504ff1ee5dc7953672d128ce1e4aa4d8e3716eb39fe710b849c64b20945
-rw-r--r-- vagrant/vagrant      355 2019-02-20 18:53 index.json
-rw-r--r-- vagrant/vagrant       31 2019-02-20 18:53 oci-layout
```
and finally

```
vagrant@ubuntu-bionic:~$ singularity build lolcow_from_oci_archive.sif oci-archive://lolcow.tar 
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:9fb6c798fa41e509b58bccc5c29654c3ff4648b608f5daa67c1aab6a7d02c118
Skipping fetch of repeat blob sha256:3b61febd4aefe982e0cb9c696d415137384d1a01052b50a85aae46439e15e49a
Skipping fetch of repeat blob sha256:9d99b9777eb02b8943c0e72d7a7baec5c782f8fd976825c9d3fb48b3101aacc2
Skipping fetch of repeat blob sha256:d010c8cf75d7eb5d2504d5ffa0d19696e8d745a457dd8d28ec6dd41d3763617e
Skipping fetch of repeat blob sha256:7fac07fb303e0589b9c23e6f49d5dc1ff9d6f3c8c88cabe768b430bdb47f03a9
Skipping fetch of repeat blob sha256:8e860504ff1ee5dc7953672d128ce1e4aa4d8e3716eb39fe710b849c64b20945
Copying config sha256:73d5b1025fbfa138f2cacf45bbf3f61f7de891559fa25b28ab365c7d9c3cbd82
 3.33 KiB / 3.33 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: lolcow_from_oci_archive.sif
```
Which runs ...

```vagrant@ubuntu-bionic:~$ ./lolcow_from_oci_archive.sif
 _______________________________________
/ Q: How do you save a drowning lawyer? \
\ A: Throw him a rock.                  /
 ---------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

2019-02-20 19:09 UTC, syl-ilumb commented on singularity_and_docker.rst
> +    $ singularity inspect --env
I added the tar file layout to the docs ...

2019-02-21 16:40 UTC, syl-ilumb commented on singularity_and_docker.rst
> +Container Metadata
By referencing the env & metadata section, this section was reduced by about 50% in size. All that remains is Docker-specific content that connects back with execution precedence.

2019-02-22 00:14 UTC, syl-ilumb commented on singularity_and_docker.rst
> +    $ singularity inspect --env
Agreed. Edited as suggested. Thanks!

2019-02-22 00:24 UTC, syl-ilumb commented on singularity_and_docker.rst
> +    $ singularity inspect --env
Agreed - reorganized as suggested. Thx!

2019-02-22 00:38 UTC, syl-ilumb commented on singularity_and_docker.rst
> +    $ singularity inspect --env
Well, that's embarrassing! 10 edits applied. Glad you caught them - thanks!

2019-02-22 00:41 UTC, syl-ilumb commented on singularity_and_docker.rst
> +    $ singularity inspect --env
Unfortunately, owing to edits applied, the context of this comment has been lost. Can you please re-state it relative to the updated content?

2019-02-22 17:06 UTC, GodloveD approved these changes

2019-02-22 17:07 UTC, GodloveD commented
:shipit:

2019-02-22 17:07 UTC, merged