[Appendix section] Environment variables supported by Singularity
apptainer/singularity-userdocs pull request #65
Opened 2019-01-14 13:29 UTC by jchavezlavalle

Fixes #51

## Description of the Pull Request (PR):

Description of all environment variables supported by Singularity on Appendix section.

## This fixes or addresses the following GitHub issues:

- Fixes #51

2019-01-19 13:57 UTC, sushma-98 commented on appendix.rst
> +
Not a grammatical expert myself - 'more than one parameter is' sounds right to me.

2019-01-19 14:09 UTC, sushma-98 approved these changes
Everything is precise and easily understandable!

2019-01-19 21:02 UTC, GodloveD requested changes
Heya @devprincess this is a great start!  But I still think it needs some more ❤️.  

I have some news... I think there are many, many more env vars to document.  Try entering the source code directory and running the following command `grep -R envkey *`.  That should give you most of them.  I think the `SINGULARITY_ENV*` variables (and the prepend, append, and path) vars must also be documented.

2019-01-19 21:02 UTC, GodloveD commented on appendix.rst
> +#. **SINGULARITY_BINDPATH** and **SINGULARITY_BIND**: Path to bind between the host and the container.
I think these descriptions need to be a little more detailed.  For instance, I think this one should read a bit more like: 
```
Comma seperated  ``source<:dest>``list of paths to bind between the host and the container.
```

2019-01-19 21:02 UTC, GodloveD commented on appendix.rst
>  .. _build-library-module:
I think the build modules need to all be pushed down a level now into subheadings since there will now be more than one section in the appendix.

2019-01-21 01:05 UTC, devprincess commented
Added a whole bunch of more env vars, please do let me know any review thank you! @GodloveD

2019-01-26 02:20 UTC, GodloveD requested changes
Thanks for filling in these variables.  It's getting closer.  

Can you also please describe the following in some way:

`SINGULARITYENV_*` allows you to transpose variables into the container at runtime
`SINGULARITYENV_PREPEND_PATH`
`SINGULARITYENV_APPEND_PATH`
`SINGULARITYENV_PATH`
^ these are all described in the env and metadata page you just wrote but should be catalogued here.

And can you also, pretty-please, alphabetize this list.  🙏

2019-01-28 15:50 UTC, devprincess commented
@GodloveD just updated this one lmk, thanks!

2019-01-31 02:32 UTC, GodloveD approved these changes
Thank you for all of the hard work @devprincess !  lgtm.  :shipit:

2019-01-31 02:33 UTC, GodloveD commented
Thank you @sushma-98 and @devprincess !

2019-01-31 02:33 UTC, merged