Update install
apptainer/singularity-userdocs pull request #7
Opened 2018-08-24 16:40 UTC by jmstover

Update more sections of the install instructions

2018-08-24 16:52 UTC, jchavezlavalle requested changes

2018-08-24 16:52 UTC, devprincess commented on installation.rst
> +Let's say that we installed Singularity to ``/usr/local``. To remove it completely,
Rst is very sensitive with characters, could you rollback this change? other than this I don't see other problems @jmstover

2018-08-24 17:27 UTC, GodloveD commented on installation.rst
> +Let's say that we installed Singularity to ``/usr/local``. To remove it completely,
Wait, are these for the 2.6 version of the docs?  Shouldn't we just be telling users to checkout out the 2.6 tag?  These look like instructions for installing 3.0.

2018-08-24 17:29 UTC, GodloveD requested changes

2018-08-24 17:29 UTC, GodloveD commented on installation.rst
>  The following commands will install the latest version of the `GitHub
Let's just change this to say that 
```
The following commands will install version 2.6
```
Or something along those lines.  And then just add the `git checkout 2.6` command.  These are the 2.6 docs after all.

2018-08-24 17:30 UTC, GodloveD commented
Also, thanks very much for grabbing this @jmstover

2018-08-24 17:40 UTC, jmstover commented on installation.rst
> +Let's say that we installed Singularity to ``/usr/local``. To remove it completely,
The docs are mixed here because of _how_ they are written. They need a thorough go through, and I'm just trying to patch them for now.

2018-08-24 23:21 UTC, jmstover commented on installation.rst
> +Let's say that we installed Singularity to ``/usr/local``. To remove it completely,
@devprincess  ... No, I can't revert the character. For me in the RST file, it shows up as `â<80><99>` .... pasting that back in gives that literal string, and not the value you need.

2018-08-27 14:35 UTC, GodloveD requested changes

2018-08-27 14:35 UTC, GodloveD commented on installation.rst
>  Install the development branch
I think this line needs to be released right?  There is no such thing as the development branch right?

2018-08-27 14:41 UTC, devprincess commented on installation.rst
>  Install the development branch
@GodloveD hey Dave, no there's no dev branch by the moment, all branches correspond to the respective releases by now and master has all the changes up-to-date (so it's like master is a dev branch by the moment)

2018-08-27 15:19 UTC, GodloveD commented on installation.rst
>  Install the development branch
Oh sorry. I read this in context and it looks good to me.

2018-08-27 15:19 UTC, GodloveD approved these changes

2018-08-27 21:21 UTC, closed without merging