Cloud library Page
apptainer/singularity-userdocs pull request #79
Opened 2019-01-25 19:25 UTC by WestleyK

## Description of the Pull Request (PR):

This PR will add a Cloud Library page. This will cover: Making a account, Making a access token, `pull` command, `push` command, and the remote builder

## This fixes or addresses the following GitHub issues:

- Fixes #72

2019-01-28 15:30 UTC, jchavezlavalle requested changes

2019-01-28 15:30 UTC, devprincess commented on cloud_library.rst
> +We also pervide a :ref:`Remote Builder <remote_builder>`, this is used for building your containers remotly,
pervide -> provide, remotly -> remotely, advantags -> advantages

2019-01-28 15:30 UTC, devprincess commented on cloud_library.rst
> + - Usally fast.
Usually

2019-01-28 15:30 UTC, devprincess commented on cloud_library.rst
> + - Can build directly to the library without the need to :ref:`push <push>` your container after. (only thrught the web GUI)
only **through**

2019-01-28 15:30 UTC, devprincess commented on cloud_library.rst
> +Make a Acount
an Account

2019-01-28 15:30 UTC, devprincess commented on cloud_library.rst
> +Makeing a acount is easy, and straightforward:
Making an account

2019-01-28 15:30 UTC, devprincess commented on cloud_library.rst
> + 4. Type your passwords, and thats it!
that's it

2019-01-28 15:30 UTC, devprincess commented on cloud_library.rst
> +The ``singularity push`` will push a container to the container library with the givin URL. Heres an example of a typical push command:
with the **given** URL. **Here's** an example...

2019-01-28 15:30 UTC, devprincess commented on cloud_library.rst
> +The ``:latest`` is the contianer tag. Tags are used to have difrent version of the same container. Heres an example:
container, different, Here's

2019-01-28 15:30 UTC, devprincess commented on cloud_library.rst
> +Lets assume you have your container (v1.0.1), and you want to push that container without deleting your ``:latest`` container, then you can add a version tag to that container, like so:
Let's

2019-01-28 15:30 UTC, devprincess commented on cloud_library.rst
> +You can download the container with that tag by replacing the ``:latest``, with the taged container you want to download.
tagged container

2019-01-28 15:30 UTC, devprincess commented on cloud_library.rst
> +    When pulling from Docker, the container will automaticly be converted to a SIF (Singularity Image Format) container.
automatically

2019-01-28 15:30 UTC, devprincess commented on cloud_library.rst
> +Heres a typical pull command:
Here's

2019-01-28 15:30 UTC, devprincess commented on cloud_library.rst
> +    If theres no tag after the container name, Singularity will pull the container with the ``:latest`` tag.
If there's

2019-01-28 15:30 UTC, devprincess commented on cloud_library.rst
> +    When pulling from Docker, the container will automaticly be converted to a SIF (Singularity Image Format) container.
automatically

2019-01-28 15:30 UTC, devprincess commented on cloud_library.rst
> +Heres a typical pull command:
Here's

2019-01-28 15:30 UTC, devprincess commented on cloud_library.rst
> +If theres no tag after the container name, Singularity will pull the container with the latest tag.
there's

2019-01-28 15:30 UTC, devprincess commented on cloud_library.rst
> +To pull a container with a spicific tag, just add the tag to the library URL:
specific

2019-01-28 15:30 UTC, devprincess commented on cloud_library.rst
> +Of course you can pull your own containers. Heres what that will look like:
comma after "Of course", also typo in Here's

2019-01-28 15:30 UTC, devprincess commented on cloud_library.rst
> +    # or use a difrent tag:
typo in different

2019-01-28 15:30 UTC, devprincess commented on cloud_library.rst
> +    You dont have to specify a output file, one will be created automaticly, but its good practice to always
typos : don't, automatically , it's

2019-01-28 15:30 UTC, devprincess commented on cloud_library.rst
> +When it come to searching the library, you could always go to: https://cloud.sylabs.io/library and search from there.
When it **comes** to searching the library...

2019-01-28 15:30 UTC, devprincess commented on cloud_library.rst
> +Here is a example for searching the library for ``centos``:
an example

2019-01-29 15:08 UTC, jchavezlavalle requested changes

2019-01-29 15:08 UTC, devprincess commented on cloud_library.rst
> + 3. Select you method to sign in, with Google, GitHub, GitLab, or Microsoft.
your method

2019-01-29 15:08 UTC, devprincess commented on cloud_library.rst
> +When it comes to searching the library, you could always go to: https://cloud.sylabs.io/library and search from there.
add link hyperref here

2019-01-29 15:08 UTC, devprincess commented on cloud_library.rst
> +The remote builder service can build your container remotly, (you dont need root access
remotely, don't

2019-01-29 15:08 UTC, devprincess commented on cloud_library.rst
> +Building from a defition file:
definition

2019-01-29 15:08 UTC, devprincess commented on cloud_library.rst
> +This is are defition file, lets call it ``ubuntu.def``:
definition, let's

2019-02-15 10:46 UTC, jchavezlavalle submitted a review, later dismissed

2019-02-15 10:46 UTC, devprincess commented on cloud_library.rst
> +witch allows you to build containers without root access
**which** allows you...

2019-04-24 03:59 UTC, GodloveD approved these changes
made a few changes and now it lgtm.  :shipit:

2019-04-24 04:03 UTC, merged

2019-04-24 15:06 UTC, WestleyK commented
Thanks @GodloveD for fixing this up!