First draft for Build environment section
apptainer/singularity-userdocs pull request #91
Opened 2019-02-07 09:24 UTC by devprincess

## Description of the Pull Request (PR):

First draft on build environment section for 3.0 

## This fixes or addresses the following GitHub issues:

- Fixes #85

2019-02-27 02:28 UTC, WestleyK requested changes
One small change, otherwise it looks good!

2019-02-27 02:28 UTC, WestleyK commented on build_env.rst
> +
Again, I would add the `library` here:

```suggestion 
    $HOME/.singularity/cache/library
```

2019-03-02 22:36 UTC, GodloveD requested changes
Heya @devprincess.  Sorry it took me so long to get around to reviewing this page!!  😩 

Looks like it still needs some love.  In particular, I'm afraid that it has some info in it that is no longer current as of 3.0.

2019-03-02 22:36 UTC, GodloveD commented on build_env.rst
> +.. _sec:buildenv:
please add on overview section.  😸

2019-03-02 22:36 UTC, GodloveD commented on build_env.rst
> +
I was just about to comment that this discussion seems to ommit the library cache.  I see that @WestleyK has beaten me to it. 

Here's what I'm seeing in the cache after building alpine images from docker hub, library, and shub:

```
vagrant@vagrant:~$ tree .singularity/cache/
.singularity/cache/
├── library
│   └── sha256.69ce2a3dcc6d3e559e20ced0df251046ee6ecff390a945d856fe0dcb3bcb3ce8
│       └── alpine_latest.sif
├── oci
│   ├── blobs
│   │   └── sha256
│   │       ├── 57c41aa0b96eb7fcf351321550126306e1da1bc1b1c1c847f4976fd201d95ba1
│   │       ├── 650605be53547aeeb66575b82b865ac86f8f4e3e5026ee7f0305426dcaae9ea6
│   │       └── 6c40cc604d8e4c121adcb6b0bfe8bb038815c350980090e74aa5a6423f8f82c0
│   ├── index.json
│   └── oci-layout
└── oci-tmp
    └── b3dbf31b77fd99d9c08f780ce6f5282aba076d70a513a8be859d8d3a4d0c92b8
        └── alpine_latest.sif
```

2019-03-02 22:36 UTC, GodloveD commented on build_env.rst
> +Remember that when you run commands as sudo this will use root’s home at ``/root`` and not your user’s home.
Maybe it is also useful to add a note here about using the `-E` option when running as root so that `SINGULARITY_CACHEDIR` will be passed along and respected.

2019-03-02 22:36 UTC, GodloveD commented on build_env.rst
> +environment.
Or use the `-E` option with `sudo`.  (I think.  Haven't actually tested that this works, but I see no reason it would not.)

2019-03-02 22:36 UTC, GodloveD commented on build_env.rst
> +between variables defined at runtime, and pre-defined defaults. By way
This is no longer true in 3.0.  Come to think of it, I don't think it was ever true.  Maybe build-specific env vars were parsed in python, but many env vars were simply parsed using bash.  Now they are all parsed using Cobra in Go.  Defaults are set in the cli code. 

Now the order of operations is as follows.  

1.  If a flag is represented by both a CLI option and a env var, and both are set, the CLI option takes precedence.  This is true for all env vars except for `SINGULARITY_BIND`/`SINGULARITY_BINDPATH` which is _combined_ with the `--bind` option, argument pair if both are present.
2. env vars overwrite default values in the CLI code
3. Any defaults in the CLI code are applied.

2019-03-02 22:36 UTC, GodloveD commented on build_env.rst
> +    ("yes", "true", "t", "1","y")
I don't think this is true anymore.  Don't know how we are handling bools.  I _think_ it should be that non-empty indicates `true`.  So if you set `export SINGULARITY_SOMEBOOL=false` it should be set as true because it is non-empty.  Should be tested I think.

2019-03-02 22:36 UTC, GodloveD commented on build_env.rst
> +**SINGULARITY_PULLFOLDER** While this isn’t relevant for build, since
Please test everything to make sure it is working as you write docs.  See: https://github.com/sylabs/singularity/issues/2788

2019-03-02 22:36 UTC, GodloveD commented on build_env.rst
> +**DOCKER_API_BASE** Set as ``index.docker.io``, which is the name of the registry. In
@devprincess can you please test and verify whether the `DOCKER*` vars actually do anything with respect to 3.0?  I'm guessing they probably do not.

2019-03-02 22:36 UTC, GodloveD commented on build_env.rst
> +**SINGULARITY_NOHTTPS** This is relevant if you want to use a
There are a few other variables that are very important here right?  
```
SINGULARITY_DOCKER_LOGIN
SINGULARITY_DOCKER_USERNAME
SINGULARITY_DOCKER_PASSWORD
```
Also there are some variables that are important for building from library:
```
SINGULARITY_BUILDER
SINGULARITY_LIBRARY
SINGULARITY_REMOTE
```
And maybe there are some other vars I'm forgetting?

2019-03-08 19:28 UTC, WestleyK approved these changes
Looks Good to me!!! :+1:

2019-03-12 11:57 UTC, closed without merging