First draft on Build environment section -> 3.1
apptainer/singularity-userdocs pull request #92
Opened 2019-02-07 10:20 UTC by devprincess

## Description of the Pull Request (PR):

Build environment section for 3.1 with cache commands

## This fixes or addresses the following GitHub issues:

- Fixes #85

2019-02-18 05:29 UTC, WestleyK requested changes
Looks great! Have a couple changes to suggest.

2019-02-18 05:29 UTC, WestleyK commented on build_env.rst
> +
.1 Not just the `pull` command, also `exec`, `shell`, `build` `run`, and `instance`.
.2 Not just the layers are cache, but whole containers when pulled/exec... from the library.

2019-02-18 05:29 UTC, WestleyK commented on build_env.rst
> +
And the library:

```
$HOME/.singularity/cache/library
```

2019-02-18 05:29 UTC, WestleyK commented on build_env.rst
> +
The `cache clean/list` is a nice new command, but I think it can be shortened/cleaned a bit, like this:

```
--------------
Cache commands
--------------

Singularity 3.1 comes with new commands for cleaning and listing the cache image files generated.

Listing cache
-------------

For example, you can list cached images and check which type they belong to: (Library or oci)

.. code-block:: none

    $ singularity cache list
    NAME                   DATE CREATED           SIZE             TYPE
    ubuntu_latest.sif      2019-02-17 20:41:15    28.11 Mb         library
    ubuntu_18.04.sif       2019-02-17 20:41:35    27.98 Mb         library
    alpine_3.8.sif         2019-02-09 20:26:57    2.18 Mb          library
    centos_latest.sif      2019-02-17 20:42:09    72.96 Mb         library
    centos_latest.sif      2019-02-17 20:42:50    73.45 Mb         oci
    ubuntu_latest.sif      2019-02-17 20:43:15    28.00 Mb         oci
    alpine_latest.sif      2019-02-09 20:26:38    2.72 Mb          oci
    alpine_3.8.sif         2019-02-09 20:27:07    2.19 Mb          oci
    
    There are 15 oci blob file(s) using 112.51 Mb of space. Use: '-T=blob' to list

You can also clean up specific type of cache by running:

You can also clean a specific cache type, chose between: ``library``, ``oci``, ``blob``
(seprated by commas)

.. code-block:: none

    # clean only blob cache:
    $ singularity cache list --type=blob

    # clean only library, and oci cache:
    $ singularity cache list --type=library,oci

*In the abuve example we are using ``cache list``, but you can also use ``cache clean``.*

Cleaning cache
--------------

Most of the ``cache clean``/``cache list`` flags can be interchanged, (``--name`` is only for ``cache clean``).

By running this: (with no arguments)

..code-block:: none

    singularity cache clean

By default this will just clean the blob cache, but if you do:

..code-block:: none

    singularity cache clean --all

This will clean all cache.
```

2019-02-18 05:29 UTC, WestleyK commented on build_env.rst
> +    singularity exec docker://busybox /bin/sh
I would put a `$` here:

```suggestion
    $ singularity exec docker://busybox /bin/sh
```

2019-02-20 00:04 UTC, devprincess commented
heya @WestleyK could you check if all the changes you suggested are addressed? thanks !

2019-02-27 02:23 UTC, WestleyK requested changes
A couple more changes. Looks good! (sorry I'm a little late)...

2019-02-27 02:23 UTC, WestleyK commented on build_env.rst
> +
I would change all the `cache clean`, to `cache list`, because this code block is in the `cache list` section.

2019-02-27 02:23 UTC, WestleyK commented on build_env.rst
> +  This feature of passing additional flags with comma-separated arguments can also be used with the ```singularity cache clean`` command we will see below.
I think theres a extra '`' here: 

```suggestion 
  This feature of passing additional flags with comma-separated arguments can also be used with the ``singularity cache clean`` command we will see below.
```

2019-02-27 02:23 UTC, WestleyK commented on installation.rst
> +    $ export VERSION=3.0.1 && # adjust this as necessary \
The latest stable release is 3.1 I believe...

2019-03-11 12:50 UTC, closed without merging