Updated default bind points
apptainer/singularity-userdocs pull request #98
Opened 2019-02-18 05:40 UTC by WestleyK

## Description of the Pull Request (PR):

This PR adds all the default bind points.

## This fixes or addresses the following GitHub issues:

- Fixes #88

2019-02-20 09:08 UTC, jchavezlavalle requested changes

2019-02-20 09:08 UTC, devprincess commented on bind_paths_and_mounts.rst
> +are the system-defined bind paths.
maybe at this point the `<path from host>:<path from container>` notation isn't clear to the user since the `-b` flag is explained below.. could be good idea to add something to this paragraph like.. 

`Where the first part of the string before ":" is the path from the host and the second part is the path from the container`

2019-02-20 23:22 UTC, jchavezlavalle approved these changes
lgtm! @WestleyK please make sure to rebase to master :+1:

2019-02-22 16:49 UTC, GodloveD commented
There seems to be some instances in which `/etc/localtime` is a default bind and some in which it is not.  Are other files also like this?  @WestleyK can you investigate before we merge?

2019-03-19 16:09 UTC, GodloveD approved these changes
I think this is fine to merge. I think it needs to be refined a bit more (maybe after merging) though.  For instance, `/etc/localtime` will also be automagically bind mounted into the container, but only if it exists in the container as a place to go right?

2019-03-19 16:09 UTC, merged